### DISCUSSION TITLE
postgres-data permission

### DISCUSSION THREAD

**Discussion by ayushbindlish** [docker-library/postgres#1088] [General]
Hi,

I am trying to upload postgres-data dir mount to GitHub. But due to the permissions issue, I am not able to do so.

```
sudo ls -lart postgres-data                                                                                                                                                                             
total 136
-rw-------  1   999 docker     3 May 26 11:43 PG_VERSION
drwx------  2   999 docker  4096 May 26 11:43 pg_twophase
drwx------  2   999 docker  4096 May 26 11:43 pg_tblspc
drwx------  2   999 docker  4096 May 26 11:43 pg_stat_tmp
drwx------  2   999 docker  4096 May 26 11:43 pg_snapshots
drwx------  2   999 docker  4096 May 26 11:43 pg_serial
drwx------  2   999 docker  4096 May 26 11:43 pg_replslot
drwx------  2   999 docker  4096 May 26 11:43 pg_notify
drwx------  4   999 docker  4096 May 26 11:43 pg_multixact
drwx------  2   999 docker  4096 May 26 11:43 pg_dynshmem
drwx------  2   999 docker  4096 May 26 11:43 pg_commit_ts
-rw-------  1   999 docker 29525 May 26 11:43 postgresql.conf
-rw-------  1   999 docker    88 May 26 11:43 postgresql.auto.conf
-rw-------  1   999 docker  1636 May 26 11:43 pg_ident.conf
drwx------  2   999 docker  4096 May 26 11:43 pg_xact
drwx------  2   999 docker  4096 May 26 11:43 pg_subtrans
-rw-------  1   999 docker  4821 May 26 11:43 pg_hba.conf
drwx------  6   999 docker  4096 May 26 11:43 base
drwxrwxr-x  9 ayush ayush   4096 May 26 11:47 ..
drwx------ 19   999 ayush   4096 May 26 11:47 .
-rw-------  1   999 docker    36 May 26 11:47 postmaster.opts
drwx------  2   999 docker  4096 May 26 11:47 pg_stat
drwx------  4   999 docker  4096 May 26 12:05 pg_logical
drwx------  2   999 docker  4096 May 26 12:05 global
-rw-------  1   999 docker    80 May 26 12:05 postmaster.pid
drwx------  3   999 docker  4096 May 26 12:05 pg_wal
```

I have the following docker-compose file:
```
version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
#    user: root
    environment:
      POSTGRES_USER: duser
      POSTGRES_PASSWORD: dpassword
      POSTGRES_DB: test
      PGDATA: /home/data
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/home/data:rwx
      - ./psql_schema.sql:/docker-entrypoint-initdb.d/psql_schema.sql
```

In the Postgres docker file, I see the gid is being set to 999. Can somebody please explain this?
https://github.com/docker-library/postgres/blob/a23c0e97980edae5be2cd4eb68ff1f0762d031cd/15/bullseye/Dockerfile#L11
