### DISCUSSION TITLE
Set max_locks_per_transaction on postgres docker image in github actions workflow file

### DISCUSSION THREAD

**Discussion by toruncem** [docker-library/postgres#1091] [General]
Hello! I was wondering what the right away to configure max_locks_per_transaction this is in a github actions workflow file given I am using a docker postgres image

Current my yaml file looks something like this
```yaml
jobs:
pytest:
runs-on:
group: 'Default Larger Runners'
services:
db:
image: postgres:14
env:
POSTGRES_USER: x
POSTGRES_DB: x
POSTGRES_PASSWORD: x
ports:
- 5432
- uses: actions/checkout@v3
- name: Setup Python
id: setup_python
uses: actions/setup-python@v4
with:
python-version: '3.9'
```
then come other configs then eventually I run pytest with
```yaml
name: Run pytest check
run: PYTHONPATH=. venv/bin/python3 -m pytest -v . -n auto
env:
ENV: "TESTING"
HOST: "0.0.0.0"
DB_HOST: localhost
DB_PORT: ${{job.services.db.ports['5432']}}
DB_BASE: x
DB_USER: x
DB_PASS: x
```
But I'm not sure how to set max_locks_per_transaction in this file such that I can avoid an error during pytest in Github Actions due to this error:

PG::OutOfMemory: ERROR: out of shared memory
HINT: You might need to increase max_locks_per_transaction.

**Comment by yosifkit** [comment]
I would assume that it is something like `command: [ "-c", "max_locks_per_transaction=..." ]` but I can't find if GitHub Actions has support for setting a command for a `service` like GitLab has.  Maybe an `args` under `services.db` like [`runs.args`](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsargs)?

Related: https://github.com/docker-library/postgres/issues/968#issuecomment-1162439212

Alternatively, overriding the `conf.sample` file (https://github.com/docker-library/postgres/issues/1060#issuecomment-1476769178) or just doing `docker run -d postgres:14 ...` directly in a `run` step could work.

**Reply by toruncem** [reply]
Thanks for the reply!

I found in this post (https://stackoverflow.com/questions/65438055/how-to-add-config-args-to-postgres-service-container-in-github-action) that _There does not seem to be a way to inject commands into services currently so that you can turn off the rsync feature. Github actions uses create command which does not support the -c attribute._

For using runs.args, could you provide an example of how I would implement that in my current workflow file, I'm not entirely sure.

For https://github.com/docker-library/postgres/issues/968#issuecomment-1162439212, it doesn't seem like `docker create options` supports `max_locks_per_transaction`.

Fairly new to this stuff so any help is appreciated!

**Reply by yosifkit** [reply]
I don't know if using `run.args` works within a `service`, since it is not documented that way. But it would be something like this:

```yaml
services:
  db:
    image: postgres:14
# json list syntax
    args: [ "-c", "max_locks_per_transaction=12345" ]
# or yaml list syntax
    args:
      - -c
      - max_locks_per_transaction=12345
```

The `-c` and its argument are arguments to the `postgres` binary in the image, not to `docker` itself. The entrypoint script from the image passes along any of its arguments to `postgres`, so they can easily be passed from the command line. The `docker run` (or `docker create`) would be something like this:

```console
$ docker run -d -e POSTGRES_USER=user -e POSTGRES_DB=db -e POSTGRES_PASSWORD=secret postgres:14 -c max_locks_per_transaction=12345
```
(Personally, I just ignore using `services` since they have this config limitation and just do the `docker run` directly.)

**Reply by toruncem** [reply]
Yeah with the json list or the yaml list syntax the error I get is from github actions is `The workflow is not valid. .github/workflows/tests.yml (Line: 17, Col: 9): Unexpected value 'args'`

Doing the `docker run` might have to be the way to go.

How would I incorporate the code you shared, 

`docker run -d -e POSTGRES_USER=user -e POSTGRES_DB=db -e POSTGRES_PASSWORD=secret postgres:14 -c max_locks_per_transaction=12345`

into my Github actions workflow file then?

Thanks again!

**Reply by toruncem** [reply]
My workflow file looks something like this for context:

```yaml
name: CI

on: [push]

jobs:

  test:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports: ['5432:5432']
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Test with black
        run: |
          python -m black --check .
      - name: Test with pytest
        env:
          DATABASE_URL: 'postgres://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}/postgres'
        run: |
          python -m pytest
```

Pardon the formatting, couldn't get all of it in the code block haha

**Reply by tianon** [reply]
Replace this:
```yaml
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports: ['5432:5432']
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
```
with something like this: (untested, but hopefully gives you enough of the right shape that you can get it working if it doesn't :innocent:)
```yaml
    steps:
      - name: Start PostgreSQL
        run: |
          docker run -d --name postgres --env POSTGRES_USER=postgres --env POSTGRES_PASSWORD=postgres --env POSTGRES_DB=postgres --publish 5432:5432 --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5 postgres:11
```
