### DISCUSSION TITLE
Multiple users with docker-compose

### DISCUSSION THREAD

**Discussion by eldarj** [docker-library/postgres#1152] [General]
Given a simple docker-compose
```
version: '3.8'

services:
  psql:
    image: postgres:16-alpine
    container_name: my-psql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=something
      - POSTGRES_PASSWORD=something
      - POSTGRES_DB=sample
```

What is the suggest approach for creating multiple users? Ideally with the logic in docker-compose alone. Or if not possible, perhaps with a sh script, but without custom Dockerfiles.
