### DISCUSSION TITLE
SQL files under docker-entrypoint-initdb.d executed but tables not created

### DISCUSSION THREAD

**Discussion by SimoneGiusso** [docker-library/postgres#1227] [General]
According to the documentation running `docker compose` on this yaml file:

```yaml
services:
  masterdb:
    image: postgres:15.6-alpine
    container_name: primary-server
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: psw
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  readonlydb:
    image: postgres:15.6-alpine
    container_name: hot-standby
    ports:
      - 5430:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: psw
```

should initialise:

primary-server with init.sql.

However it does not happen even if the file is correctly mounted:

<img width="901" alt="Screenshot 2024-04-13 at 22 21 18" src="https://github.com/docker-library/postgres/assets/26305592/998b708a-41ca-4c02-86e3-bbc9e6569c02">

Ii tried, to delete/re build the images, delete all the volumes but nothing. The `init.sql` script is not executed.
