### DISCUSSION TITLE
Please help, I have persisted it, but the table and data are not restored after restarting the container.

### DISCUSSION THREAD

**Discussion by llnancy** [docker-library/postgres#1256] [General]
verion: postgres:15-alpine

Persistent mount (Similar to the following, I am sure that the persistent mounting of the data volume is successful): 

```yml
volumeMounts:
- name: postgresql
  mountPath: /var/lib/postgresql
```

After restarting the container, the files in the directory are still there, 

![image](https://github.com/docker-library/postgres/assets/40930677/1c2bdd8d-2113-4fd2-bd52-9a8c8d3b347a)

but the previous database and table are gone. Is there a way to restore it? How can I do it?
