### DISCUSSION TITLE
postgres:13 and  dpage/pgadmin4 is not installed

### DISCUSSION THREAD

**Discussion by jamessv** [docker-library/postgres#1276] [General]
I am using docker compose on windows 10, 64 here is the source code

```yaml
#postgres
#pgadmin


version: '3.8'

services:
 postgres:
  image: postgres:13
  container_name: postgres
  restart: on-failure
  environment:
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: postgres
   POSTGRES_DB: postgres
  ports:
   - '5432:5432'
  volumes:
   - postgres:/var/lib/postgresql/data
  healthcheck:
   test: ['CMD', 'pg_isready', '-U', 'auth']
   interval: 30s
   timeout: 30s
   retries: 3
   
 pgadmin:
  image: dpage/pgadmin4
  container_name: pgadmin
  restart: on-failure
  environment:
   PGADMIN_DEFAULT_EMAIL: admin@example.com
   PGADMIN_DEFAULT_PASSWORD: admin
  ports:
   - '5050:80'
   - '5051:443'

volumes:
 postgres:
```

here is the error

```console
$ docker-compose up
Starting pgadmin  ... done
Starting postgres ... done
Attaching to pgadmin, postgres
postgres    | popen failure: Cannot allocate memory
postgres    | initdb: error: The program "postgres" is needed by initdb but was not found in the
postgres    | same directory as "/usr/lib/postgresql/13/bin/initdb".
postgres    | Check your installation.
pgadmin     | postfix/postlog: starting the Postfix mail system
postgres    | popen failure: Cannot allocate memory
postgres    | initdb: error: The program "postgres" is needed by initdb but was not found in the
postgres    | same directory as "/usr/lib/postgresql/13/bin/initdb".
postgres    | Check your installation.
postgres exited with code 1
postgres    | popen failure: Cannot allocate memory
postgres    | initdb: error: The program "postgres" is needed by initdb but was not found in the
postgres    | same directory as "/usr/lib/postgresql/13/bin/initdb".
postgres    | Check your installation.
postgres exited with code 1
postgres    | popen failure: Cannot allocate memory
postgres    | initdb: error: The program "postgres" is needed by initdb but was not found in the
postgres    | same directory as "/usr/lib/postgresql/13/bin/initdb".
postgres    | Check your installation.
postgres exited with code 1
postgres    | popen failure: Cannot allocate memory
postgres    | initdb: error: The program "postgres" is needed by initdb but was not found in the
postgres    | same directory as "/usr/lib/postgresql/13/bin/initdb".
postgres    | Check your installation.
postgres exited with code 1
postgres    | popen failure: Cannot allocate memory
postgres    | initdb: error: The program "postgres" is needed by initdb but was not found in the
postgres    | same directory as "/usr/lib/postgresql/13/bin/initdb".
postgres    | Check your installation.
```
