### ISSUE TITLE
Spring application can't connect to postgred in docker

### ISSUE THREAD

**Issue by notkksm** [docker-library/postgres#1022]
When i try to connect my spring application with postgres in docker i have an error
`FATAL:  database "animals" does not exist` `
I read that the reason could be that i have postgres on my pc and i changed the port, but i still see the same error. What is my mistake? Thanks! ( i see it in console:
 ```
listening on IPv4 address "0.0.0.0", port 5433
db     |  LOG:  listening on IPv6 address "::", port 5433
db     | LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5433), 
```
docker-compose.yml
```
[version: '2'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5433/animals
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=darsmeved
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=darsmeved
    expose:
      - "5433"
    ports:
      - "5433:5432"
    command: -p 5433](url)
```
