### ISSUE TITLE
"data" folder is always empty

### ISSUE THREAD

**Issue by CyborTronik** [docker-library/postgres#103]
I have mounted ``` /registry:/var/lib/postgresql ``` to postgres:9.3 and 9.4.
Also mounted: create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
I see that this sql file is get executed but nothing has been created inside /var/lib/postgresql (my case /registry)  just  an empty folder called data and nothing more.
If I try to use initdb then is raised an exception that the data folder is not empty.

**Comment by Starefossen** [comment]
Could you past the full Docker run command you use to start your PostgreSQL database?

**Comment by md5** [comment]
I believe you need to mount with /registry:/var/lib/postgresql/data.

The empty “data" directory is the mount point directory created when the
Docker-managed /var/lib/postgresql/data directory is mounted.

**Comment by tgandrews** [comment]
I also see this issue with the following `docker-compose.yml`

````
db:
  image: postgres
  volumes:
    - ./data:/var/lib/postgresql
api:
  build: ./api
  links:
    - db
  volumes:
    - ./api:/myapp
````

Is there something I'm missing?
