### ISSUE TITLE
Password set via POSTGRES_PASSWORD includes literal double-quotes

### ISSUE THREAD

**Issue by mrichar1** [docker-library/postgres#1035]
I'm currently using this image (`postges:15-alpine`) with kubernetes, setting the environment variable via a Secret:

```
containers:
   - name: postgres
      image: postgres
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 5432 
      env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
```

The secret contains an alphanumeric string:

```
apiVersion: v1
data:
  # base64 decodes to: nuowef234nonou234fwe0483
  password: bnVvd2VmMjM0bm9ub3UyMzRmd2UwNDgz
kind: Secret
metadata:
  name: postgres-secret
```

If I 'exec' into the running container, I can look at the env vars:

```
/ # echo $POSTGRES_PASSWORD
nuowef234nonou234fwe0483
```

If try to connect from a different container with either psql or python client, I get a 'failed auth' message. However, if I add literal double quotes, I connect successfully:

```


/ # psql postgresql://postgres:nuowef234nonou234fwe0483@postgres.default.svc/postgres
psql: error: connection to server at "postgres.default.svc" (10.99.44.112), port 5432 failed: FATAL:  password authentication failed for user "postgres"

/ # psql postgresql://postgres:%22nuowef234nonou234fwe0483%22@postgres.default.svc/postgres
psql (15.1)
Type "help" for help.

postgres=# 
```

```
> psycopg2.connect(host="postgres.default.svc", port=5432, user="postgres", password="nuowef234nonou234fwe0483", dbname="postgres")

psycopg2.OperationalError: FATAL:  password authentication failed for user "postgres"
```

```
> psycopg2.connect(host="postgres.default.svc", port=5432, user="postgres", password="\"nuowef234nonou234fwe0483\"", dbname="postgres")

<connection object at 0x7f8cdeda42c0;>
```

Any ideas on where the extra quotes are coming from between the environment variable and the running config?
