### ISSUE TITLE
no matching manifest for linux/arm64/v8 in the manifest list entries

### ISSUE THREAD

**Issue by SirMishaa** [docker-library/postgres#1097]
Got this error when trying to pull a postgres image, it looks like an issue with the manifest or something 

```yml
services:
  postgres:
    image: postgres:15-alpine
    # platform: linux/arm64/v8 <= It does't change anything 
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: main_db
    ports:
      - 5432:5432
    volumes:
      - postgresdb_data:/var/lib/postgresql/data
    networks:
      - database
 
volumes:
  influxdb_data:
  postgresdb_data:

networks:
  database:
```

I have tried to use latest, with no success. What's happening ?
 
![image](https://github.com/docker-library/postgres/assets/42717232/61d15df7-0474-40fc-8103-9c777b68a7ca)
