### ISSUE TITLE
postgres:alpine: error column datlastsysoid does not exist

### ISSUE THREAD

**Issue by MrWildanMD** [docker-library/postgres#1134]
i got this strange error on macOS but its running fine in my linux..whats wrong?
here my compose:
```
postgresdb:
    image: postgres:alpine
    container_name: postgres_container
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
```

![5cbc21b8-0001-48a3-986e-b4333129612e](https://github.com/docker-library/postgres/assets/60354284/175a632a-e91e-456d-a790-992404d3b84f)
