### ISSUE TITLE
Unable to connect to PostgreSQL server: FATAL: password authentication failed for user "smartloy_user"

### ISSUE THREAD

**Issue by abkarim** [docker-library/postgres#1218]
Unable to login from adminer (note: I'm just starting with postgres, i have not tried to login from anything else at this point) while username and password are correct (I have checked many times)

docker-compose.yml
```
version: '3.8'
services:
  postgres_db_smartloy:
    image: postgres
    container_name: smartloydb
    restart: always
    volumes:
      - ./data/db:/var/lib/postgres/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=smartloy
      - POSTGRES_USER=smartloy_user
      - POSTGRES_PASSWORD=smartloy_353##$$
    networks:
      - smartloy

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - '8080:8080'
    networks:
      - smartloy

networks:
  smartloy:

```

![Screenshot from 2024-03-23 19-32-35](https://github.com/docker-library/postgres/assets/84965867/07eb41ce-0c4e-4824-9dfb-74aecd86b91a)

**Device:**
```
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm
```
**Docker:**
```
Client:
 Version:           20.10.24+dfsg1
 API version:       1.41
 Go version:        go1.19.8
 Git commit:        297e128
 Built:             Thu May 18 08:38:34 2023
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.24+dfsg1
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.19.8
  Git commit:       5d6db84
  Built:            Thu May 18 08:38:34 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.20~ds1
  GitCommit:        1.6.20~ds1-1+b1
 runc:
  Version:          1.1.5+ds1
  GitCommit:        1.1.5+ds1-1+deb12u1
 docker-init:
  Version:          0.19.0
  GitCommit:        

```
```
docker-compose version 1.29.2, build unknown
docker-py version: 5.0.3
CPython version: 3.11.2
OpenSSL version: OpenSSL 3.0.11 19 Sep 2023
```
