### ISSUE TITLE
Volume mapping resets every compose

### ISSUE THREAD

**Issue by RampantDespair** [docker-library/postgres#1289]
As the title states, every time I `docker compose up/down`, a new volume is created.
This causes a few issues on my end notably the loss of my previous data.

Despite having the following set in my `docker-compose.yaml`
```yaml
# Postgres
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgres
    ports:
      - "3001:5432"
    networks:
      - backend_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U ${POSTGRES_USER}"]
      interval: 3s
      timeout: 3s
      retries: 5
```

In practice I get this
![image](https://github.com/user-attachments/assets/401359b8-c040-4ae3-9d45-5fb6702d1383)

And the `postgres_data` volume is completely empty
![image](https://github.com/user-attachments/assets/e0227c9d-4ec6-4041-8662-fab4683994f2)

Surely this is an error on my end and not the expected behavior?
I'm semi-new to docker so if someone could point me in the right direction that would be much appreciated!
