### ISSUE TITLE
postgres:17-alpine3.22 not working

### ISSUE THREAD

**Issue by svenopdehipt** [docker-library/postgres#1346]
The postgres:17-alpine3.22 image is not working because alpine 3.22 changed the ICU libraries from version 74 up to version 76 [Alpine 3.21](https://pkgs.alpinelinux.org/package/v3.21/main/x86/icu) [Alpine 3.22](https://pkgs.alpinelinux.org/package/v3.22/main/x86/icu).

I add an error description below:

```
<name>  | PostgreSQL Database directory appears to contain a database; Skipping initialization
<name>  |
<name>  | Error loading shared library libicui18n.so.74: No such file or directory (needed by /usr/local/bin/postgres)
<name>  | Error loading shared library libicuuc.so.74: No such file or directory (needed by /usr/local/bin/postgres)
<name>  | Error relocating /usr/local/bin/postgres: ucol_getVersion_74: symbol not found
<name>  | Error relocating /usr/local/bin/postgres: uloc_getLanguage_74: symbol not found
<name>  | Error relocating /usr/local/bin/postgres: u_isprint_74: symbol not found
<name>  | Error relocating /usr/local/bin/postgres: u_isupper_74: symbol not found
<name>  | Error relocating /usr/local/bin/postgres: ucol_open_74: symbol not found
<name>  | Error relocating /usr/local/bin/postgres: u_strToTitle_74: symbol not found
<name>  | Error relocating /usr/local/bin/postgres: ucol_getSortKey_74: symbol not found
<name>  | Error relocating /usr/local/bin/postgres: ucol_strcoll_74: symbol not found
<name>  | Error relocating /usr/local/bin/postgres: ucol_close_74: symbol not found
<name>  | Error relocating /usr/local/bin/postgres: uloc_getAvailable_74: symbol not found
<name>  | Error relocating /usr/local/bin/postgres: ucol_nextSortKeyPart_74: symbol not found
<name>  | Error relocating /usr/local/bin/postgres: uloc_countAvailable_74: symbol not found
<name>  | Error relocating /usr/local/bin/postgres: u_strlen_74: symbol not found
<name>  | Error relocating /usr/local/bin/postgres: u_isalpha_74: symbol not found
<name>  | Error relocating /usr/local/bin/postgres: u_toupper_74: symbol not found
<name>  | Error relocating /usr/local/bin/postgres: uloc_getDisplayName_74: symbol not found
<name>  | Error relocating /usr/local/bin/postgres: uiter_setUTF8_74: symbol not found
<name>  | Error relocating /usr/local/bin/postgres: u_isgraph_74: symbol not found
<name>  | Error relocating /usr/local/bin/postgres: ucol_openRules_74: symbol not found
<name>  | Error relocating /usr/local/bin/postgres: ucnv_fromUChars_74: symbol not found
<name>  | Error relocating /usr/local/bin/postgres: ucol_getRules_74: symbol not found
<name>  | Error relocating /usr/local/bin/postgres: ucol_strcollUTF8_74: symbol not found
<name>  | Error relocating /usr/local/bin/postgres: uiter_setString_74: symbol not found
<name>  | Error relocating /usr/local/bin/postgres: u_isspace_74: symbol not found
<name>  | Error relocating /usr/local/bin/postgres: ucnv_toUChars_74: symbol not found
<name>  | Error relocating /usr/local/bin/postgres: u_errorName_74: symbol not found
<name>  | Error relocating /usr/local/bin/postgres: u_strcat_74: symbol not found
<name>  | Error relocating /usr/local/bin/postgres: u_versionToString_74: symbol not found
<name>  | Error relocating /usr/local/bin/postgres: ucnv_open_74: symbol not found
<name>  | Error relocating /usr/local/bin/postgres: uloc_toLanguageTag_74: symbol not found
<name>  | Error relocating /usr/local/bin/postgres: u_isalnum_74: symbol not found
<name>  | Error relocating /usr/local/bin/postgres: u_strcpy_74: symbol not found
<name>  | Error relocating /usr/local/bin/postgres: u_tolower_74: symbol not found
<name>  | Error relocating /usr/local/bin/postgres: u_islower_74: symbol not found
<name>  | Error relocating /usr/local/bin/postgres: u_isdigit_74: symbol not found
<name>  | Error relocating /usr/local/bin/postgres: u_ispunct_74: symbol not found
<name>  | Error relocating /usr/local/bin/postgres: u_strToUpper_74: symbol not found
<name>  | Error relocating /usr/local/bin/postgres: u_strToLower_74: symbol not found
```

**Comment by tianon** [comment]
I'm having a hard time reproducing - do you have any more clues to what's different about your environment?  A minimal way to reproduce this cleanly would help a lot.

I tried running `postgres:17-alpine3.21` to initialize a database and then ran `postgres:17-alpine3.22` on that database and didn't see any issues.

**Comment by svenopdehipt** [comment]
I have two databases, which have this problem: One for nextcloud (nextcloud:fpm-alpine) and on for matrix (matrixdotorg/synapse:latest). I have created with an way earlier version (but I don't know the exact one).

**Comment by svenopdehipt** [comment]
@tianon do you need more infos? if that is the case, please specify which information you need.

**Comment by ImreSamu** [comment]
Hi @svenopdehipt 

I've also been trying to reproduce this issue on an amd64 (x86-64) platform, but without success. 

To help diagnose the problem, could you please provide some more information?
* What is your host OS and hardware architecture? 
   * (e.g., linux/386,  arm/v6,  arm/v7, arm64/v8 , riscv64,  s390x, ppc64le, etc.) 
* Could you share the  output of
  * `docker inspect postgres:17-alpine3.21`   (I'm assuming this is one of the tags that still works for you)
  * `docker inspect postgres:17-alpine3.22`
* If possible, could you share the original` POSTGRES_INITDB_ARGS` you used to initialize the database?
* Is there anything else unique about your setup that might be relevant?

Also, if you have a minimal, 
reliable script to reproduce the issue on your machine, that would be incredibly valuable.

----

For context, I have already tested the following upgrade paths on `amd64`, 
but all of them resulted in a ~ collation version mismatch warning, not the fatal "shared library not found" error:
* postgres:17.0-alpine3.19 --> postgres:17.5-alpine3.22
* postgres:17.0-alpine3.20 --> postgres:17.5-alpine3.22
* postgres:17.1-alpine3.19 --> postgres:17.5-alpine3.22
* postgres:17.1-alpine3.20 --> postgres:17.5-alpine3.22
* postgres:17.2-alpine3.19 --> postgres:17.5-alpine3.22
* postgres:17.2-alpine3.20 --> postgres:17.5-alpine3.22
* postgres:17.2-alpine3.21 --> postgres:17.5-alpine3.22

```
docker images postgres:17*
REPOSITORY   TAG               IMAGE ID       CREATED        SIZE
postgres     17-alpine         f40315d0e8a6   7 days ago     279MB
postgres     17.5-alpine3.22   f40315d0e8a6   7 days ago     279MB
postgres     17.2-alpine3.20   a80c7517b761   4 months ago   248MB
postgres     17.2-alpine3.21   2bf60600670f   4 months ago   278MB
postgres     17.2-alpine3.19   a80eabed736f   6 months ago   254MB
postgres     17.1-alpine3.19   497199803130   7 months ago   254MB
postgres     17.1-alpine3.20   9c95018c1d23   7 months ago   254MB
postgres     17.0-alpine3.20   26f3bf9ace56   8 months ago   254MB
postgres     17.0-alpine3.19   c3c9c12576b5   8 months ago   253MB
```

**Comment by svenopdehipt** [comment]
Sorry for the delayed reply. Here are the information you requested.

```
uname -a
Linux mainserver 6.8.0-60-generic #63-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 15 19:04:15 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
```

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04.2 LTS
Release:	24.04
Codename:	noble
```

```
docker inspect postgres:17-alpine3.21
[
    {
        "Id": "sha256:ccf5f17e3e25b3e2f75f1f96f6d56abebb39dda4f66b6dcc863ad8982b7a2ad2",
        "RepoTags": [
            "postgres:17-alpine3.21"
        ],
        "RepoDigests": [
            "postgres@sha256:667a474ccd6764e3e439d3eea7a2662f74e2b92171a96628a75a4209420c9872"
        ],
        "Parent": "",
        "Comment": "buildkit.dockerfile.v0",
        "Created": "2025-06-06T18:27:47Z",
        "DockerVersion": "",
        "Author": "",
        "Config": {
            "ExposedPorts": {
                "5432/tcp": {}
            },
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "GOSU_VERSION=1.17",
                "LANG=en_US.utf8",
                "PG_MAJOR=17",
                "PG_VERSION=17.5",
                "PG_SHA256=fcb7ab38e23b264d1902cb25e6adafb4525a6ebcbd015434aeef9eda80f528d8",
                "DOCKER_PG_LLVM_DEPS=llvm19-dev \t\tclang19",
                "PGDATA=/var/lib/postgresql/data"
            ],
            "Entrypoint": [
                "docker-entrypoint.sh"
            ],
            "Cmd": [
                "postgres"
            ],
            "Volumes": {
                "/var/lib/postgresql/data": {}
            },
            "WorkingDir": "/",
            "StopSignal": "SIGINT"
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 278202905,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/4c9eb17ad4cd9ed37d3fe7685252c26381ef52c65715a1a2fcd1eb5e609e4e18/diff:/var/lib/docker/overlay2/75ec271f6b4acf3dae2d3fd34d64291a7d2e262702f13479f003aeee0dbe7e6b/diff:/var/lib/docker/overlay2/865e070803fc40d102fdb16a42b31e4fd5736bd5ccfbd6ed5ee40f0744fdb2ee/diff:/var/lib/docker/overlay2/cd3b0864eefde58fd83af689365b68ba3b11aca1cb0602a0d339c3d126002f65/diff:/var/lib/docker/overlay2/4d1213bb45c5d30a8464fef036eff4c1c691ffec8800d465b9046fdbd246b805/diff:/var/lib/docker/overlay2/19cefafc8362d409f236e8f68b67818af23c10ab3422a535e35e54898e68ec26/diff:/var/lib/docker/overlay2/b9fbc4883edad54b137bedc3f66b839c2ee85bd74d3450a30018f28cfec21022/diff:/var/lib/docker/overlay2/22359a08a2552a7c465161d02c9b560f0fa72ca54f412d38e8ff8deda57c9b36/diff:/var/lib/docker/overlay2/e93de590e1965e7f084dbb5d695a2b74b1eae555df1c41f484ce1abaef561f49/diff",
                "MergedDir": "/var/lib/docker/overlay2/f9b9a9eddb3f48665831f8282ff64cd4fc831a362bf48e8f2023d869dae3fa68/merged",
                "UpperDir": "/var/lib/docker/overlay2/f9b9a9eddb3f48665831f8282ff64cd4fc831a362bf48e8f2023d869dae3fa68/diff",
                "WorkDir": "/var/lib/docker/overlay2/f9b9a9eddb3f48665831f8282ff64cd4fc831a362bf48e8f2023d869dae3fa68/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:08000c18d16dadf9553d747a58cf44023423a9ab010aab96cf263d2216b8b350",
                "sha256:7c1165de15453dc5f26a273ca1d76b150bab9ddce099eb1e558704f1f59a13e1",
                "sha256:8405c2554960e3e096e56b60aaf291591e8cedbd568381deff6123f6f0c8b587",
                "sha256:db19ee6a235eecda09a6207b2e97af12b8b8f2a20b71f42f573dbd4e0663e7eb",
                "sha256:a4fa05d04eeebc1e2b7d3a3fb1d8857eb9f6135fb9c43b2628414181b8a94fa7",
                "sha256:cfad1fba85870bb9acc7a1aba8bab640e90e0f069a7635f9557e2348caedc7a4",
                "sha256:7d5f71d6cd717f3113b7166c231d4ee0f21d9182f6a3fa99cf4a1052b3700a94",
                "sha256:0694d8c4ca26c9fa99fb9fa63d94a8f7d6159945ff38213d6f9352fcc6b4c012",
                "sha256:c10fdb69ad17a0d848ef05a4ed8b18a1ad7f0cffa013027dd3d5b3b54d459a65",
                "sha256:61cec815d470f5b6e6e2e4b2761b728e9012a053eb04b435b6e90fa3b4e1b0cb"
            ]
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]
```

```
docker inspect postgres:17-alpine3.22
[
    {
        "Id": "sha256:f40315d0e8a6b27dcd87b69bc98f8012e8bd361f7587b5050cd9599e052cbe77",
        "RepoTags": [
            "postgres:17-alpine3.22"
        ],
        "RepoDigests": [
            "postgres@sha256:fbe21607052bb5c298674f2fd8cf044a63aa3ddf50b81627f894f91f40f50bcb"
        ],
        "Parent": "",
        "Comment": "buildkit.dockerfile.v0",
        "Created": "2025-06-06T18:27:47Z",
        "DockerVersion": "",
        "Author": "",
        "Config": {
            "ExposedPorts": {
                "5432/tcp": {}
            },
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "GOSU_VERSION=1.17",
                "LANG=en_US.utf8",
                "PG_MAJOR=17",
                "PG_VERSION=17.5",
                "PG_SHA256=fcb7ab38e23b264d1902cb25e6adafb4525a6ebcbd015434aeef9eda80f528d8",
                "DOCKER_PG_LLVM_DEPS=llvm19-dev \t\tclang19",
                "PGDATA=/var/lib/postgresql/data"
            ],
            "Entrypoint": [
                "docker-entrypoint.sh"
            ],
            "Cmd": [
                "postgres"
            ],
            "Volumes": {
                "/var/lib/postgresql/data": {}
            },
            "WorkingDir": "/",
            "StopSignal": "SIGINT"
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 278760462,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/eea64c91bf510e081432d65884d9f72ca97028f790173a39f980cb750094385a/diff:/var/lib/docker/overlay2/61e069b1dccac1b03af2a267eb31f523d5e97012a58b7eec7479889965fcd570/diff:/var/lib/docker/overlay2/de7af18a14b1c2b195493b0e0a8f62b29bd0ef6de61a1d43c0ab7fd74972fcb6/diff:/var/lib/docker/overlay2/bc426cb7e1d92365bfe4159839b6ec13862e61535bfb800d2d73e3bcad39a19c/diff:/var/lib/docker/overlay2/155575c3b812853a6c218ad07d70ffd9c13117e752a7a2466fae740b01bfa5d8/diff:/var/lib/docker/overlay2/611d810108647b5a544ec768e9b50f49321ae1a3e0b4d4d99a1bc66b42de01a3/diff:/var/lib/docker/overlay2/6162901c356f599aeab43d702d4c5cdda6e1338a127b5caf32270dc049a4eddb/diff:/var/lib/docker/overlay2/3167abe3379c1b02e2a15b6a6c102dd9b20063f3e3f344db273edc7962528c3f/diff:/var/lib/docker/overlay2/153fd02cab1ab9cb04f78382631876523071429e8e789394f7ca87032cf75703/diff",
                "MergedDir": "/var/lib/docker/overlay2/9c48a7867056e25b04469f4289352fba6fb2dc9436dae3145c7a25e31cb7ff3e/merged",
                "UpperDir": "/var/lib/docker/overlay2/9c48a7867056e25b04469f4289352fba6fb2dc9436dae3145c7a25e31cb7ff3e/diff",
                "WorkDir": "/var/lib/docker/overlay2/9c48a7867056e25b04469f4289352fba6fb2dc9436dae3145c7a25e31cb7ff3e/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:fd2758d7a50e2b78d275ee7d1c218489f2439084449d895fa17eede6c61ab2c4",
                "sha256:a670c37a1951305e73b6101a6b1cc6b37de4d73f1abdaaf36062ac0d279f5138",
                "sha256:ae94c5b0fc56f614cb9824565f90d6f17bdc1050d2d9331d9fb6583de8a490d7",
                "sha256:0ac3b956fb959a641856c8d5df2010dbcc42a5fcfea035f29618e0172c40afa0",
                "sha256:b2276f7c8ac2af6e62f1e65ea9e668942290afaef542e59c4b8bec5292eced57",
                "sha256:240002faf7ad11bfb2653cc7da7e9e2e1afb74d2213d080a24e577d9081f9485",
                "sha256:0b5565b414145aea2cfae946b94b1b179132051f09ea98903f830f4ddb900309",
                "sha256:dbd66ba91b6d60eb86485c9d4ddde35125ae675d1e478dd83f88a1ae7708a4d6",
                "sha256:383a8ae6e5906bb216ea262ec5ab3712b2cf337579fc24028a61ae91b2a8e48d",
                "sha256:1664c2c5d5acf2d17f2e61bd71bd0165463e8dbdfd4a3fb54cc4e0f9735a400d"
            ]
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]
```
Here is a part of my docker-compose.yaml (which also includes the database variables).

```
services:
  nginx:
    image: nginx:mainline-alpine
    restart: always
    ports:
      - "10.1.0.3:80:80/tcp"
      - "10.1.0.3:443:443/tcp"
      - "10.1.0.3:443:443/udp"
      - "10.1.0.3:8448:8448/tcp"
      - "10.1.0.3:8448:8448/udp"
      - "[::]:80:80/tcp"
      - "[::]:443:443/tcp"
      - "[::]:443:443/udp"
      - "[::]:8448:8448/tcp"
      - "[::]:8448:8448/udp"
    depends_on:
      - nextcloud
      - matrix
    volumes:
      - nextcloud:/var/www/html:z,ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/ssl:ro
    networks:
      - nextcloud_nginx
      - matrix_nginx

  nextcloud:
    image: nextcloud:fpm-alpine
    restart: always
    depends_on:
      - nextcloud-db
    volumes:
      - nextcloud:/var/www/html:z
      - ./nextcloud/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - /mnt/data/nextcloud:/var/www/html/data
    networks:
      - nextcloud_nginx
      - nextcloud_web_elastic
      - nextcloud_web_db
    environment:
      - OVERWRITEPROTOCOL=https
      - NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.opdehipt.com
      - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nextcloud_user
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_password
      - POSTGRES_DB_FILE=/run/secrets/nextcloud_db_name
      - POSTGRES_USER_FILE=/run/secrets/nextcloud_db_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/nextcloud_db_password
      - POSTGRES_HOST=nextcloud-db
    secrets:
      - nextcloud_user
      - nextcloud_password
      - nextcloud_db_name
      - nextcloud_db_user
      - nextcloud_db_password

  nextcloud-db:
    image: postgres:17-alpine3.21
    restart: always
    volumes:
      - nextcloud-db:/usr/local/bin/
    networks:
      - nextcloud_web_db
      - nextcloud_db_backup
    environment:
      - POSTGRES_DB_FILE=/run/secrets/nextcloud_db_name
      - POSTGRES_USER_FILE=/run/secrets/nextcloud_db_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/nextcloud_db_password
    secrets:
      - nextcloud_db_name
      - nextcloud_db_user
      - nextcloud_db_password

  nextcloud-elastic:
    image: elasticsearch:9.0.2
      # command: sh -c "bin/elasticsearch-plugin install --batch ingest-attachment; /bin/tini -s /usr/local/bin/docker-entrypoint.sh eswrapper"
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - xpack.security.http.ssl.enabled=false
    networks:
      - nextcloud_web_elastic
    deploy:
      resources:
        limits:
          memory: 4G

  nextcloud-backup:
    image: ghcr.io/borgmatic-collective/borgmatic
    restart: always
    volumes:
      - /mnt/data/nextcloud:/mnt/source/nextcloud:ro
      - ./backup/nextcloud/etc:/etc/borgmatic.d:Z
      - ./backup/ssh:/root/.ssh:Z
      - /mnt/data/backup/nextcloud:/mnt/backup
      - nextcloud-db:/usr/database:ro
    environment:
      - TZ=Europe/Berlin
      - BORG_PASSPHRASE=${NEXTCLOUD_BACKUP_PASS}
      - DB_NAME=${NEXTCLOUD_DB_NAME}
      - DB_USER=${NEXTCLOUD_DB_USER}
      - DB_PASS=${NEXTCLOUD_DB_PASS}
      - DB_HOST=nextcloud-db
    networks:
      - nextcloud_db_backup

  matrix:
    image: matrixdotorg/synapse:latest
    restart: always
    environment:
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
    volumes:
      - ./matrix:/data
      - /mnt/data/matrix/uploads:/data/uploads
      - /mnt/data/matrix/media:/data/media
      - /mnt/data/matrix/media_store:/data/media_store
    depends_on:
      - matrix-db
    networks:
      - matrix_nginx
      - matrix_db

  matrix-db:
    image: postgres:17-alpine3.21
    restart: always
    environment:
      - POSTGRES_DB_FILE=/run/secrets/matrix_db_name
      - POSTGRES_USER_FILE=/run/secrets/matrix_db_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/matrix_db_password
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - ./matrix_db:/var/lib/postgresql/data
      - matrix-db:/usr/local/bin/
    networks:
      - matrix_db
      - matrix_db_backup
    secrets:
      - matrix_db_name
      - matrix_db_user
      - matrix_db_password

  matrix-backup:
    image: ghcr.io/borgmatic-collective/borgmatic
    restart: always
    volumes:
      - /mnt/data/matrix:/mnt/source/matrix:ro
      - ./backup/matrix/etc:/etc/borgmatic.d:Z
      - ./backup/ssh:/root/.ssh:Z
      - /mnt/data/backup/matrix:/mnt/backup
      - nextcloud-db:/usr/database:ro
    environment:
      - TZ=Europe/Berlin
      - DB_NAME=${MATRIX_DB_NAME}
      - DB_USER=${MATRIX_DB_USER}
      - DB_PASS=${MATRIX_DB_PASS}
      - DB_HOST=matrix-db
      - BORG_PASSPHRASE=${MATRIX_BACKUP_PASS}
    networks:
      - matrix_db_backup

volumes:
  nextcloud:
  nextcloud-db:
  matrix-db:

networks:
  nextcloud_nginx:
    driver: bridge
  nextcloud_web_db:
    driver: bridge
  nextcloud_web_elastic:
    driver: bridge
  nextcloud_db_backup:
    driver: bridge
  matrix_nginx:
    driver: bridge
  matrix_db:
    driver: bridge
  matrix_db_backup:
    driver: bridge

secrets:
  nextcloud_user:
    file: ./secrets/nextcloud_user
  nextcloud_password:
    file: ./secrets/nextcloud_password
  nextcloud_db_name:
    file: ./secrets/nextcloud_db_name
  nextcloud_db_user:
    file: ./secrets/nextcloud_db_user
  nextcloud_db_password:
    file: ./secrets/nextcloud_db_password
  matrix_db_name:
    file: ./secrets/matrix_db_name
  matrix_db_user:
    file: ./secrets/matrix_db_user
  matrix_db_password:
    file: ./secrets/matrix_db_password
```

I didn't have the time till now to reproduce the issue with a smaller setup. I can also give you more hardware details, if you need them, because this is a self hosted server which runs at my home.

**Comment by ImreSamu** [comment]
Hi @svenopdehipt ,

Thanks for the` docker-compose.yaml.` The issue is a volume misconfiguration.
The problem is these lines in your `nextcloud-db` and `matrix-db` services:


```yaml
# In nextcloud-db service
volumes:
  - nextcloud-db:/usr/local/bin/     # <--- This is incorrect

# In matrix-db service
volumes:
  - ./matrix_db:/var/lib/postgresql/data          
  - matrix-db:/usr/local/bin/                               # <--- This is also incorrect

```

Mounting a volume to /usr/local/bin/ causes [Docker to save the old binaries](https://docs.docker.com/engine/storage/volumes/#populate-a-volume-using-a-container)  from your alpine3.21 image into the volumes. When you upgrade to `alpine3.22`, these old binaries overwrite the new ones, causing the crash. 

**You should only mount postgres volumes for data, not for postgres program binaries.**

Solution ( not tested ,  be careful ! ) 
* Re-read documentation: 
  * https://docs.docker.com/engine/storage/volumes/#populate-a-volume-using-a-container
  * https://github.com/docker-library/docs/tree/master/postgres#pgdata
* Backup your databases first (e.g., using `pg_dump` ) 
* Stop everything with docker-compose down
* Edit `docker-compose.yaml` and 
     * remove the incorrect - ...:/usr/local/bin/ lines from both Postgres services.
     * add/fix `/var/lib/postgresql/data` volumes
* Delete the old named volumes that contain the bad binaries.
* ~  You may also need to adjust your backup service volumes to align with these changes.
* Restore databases 


-------------

This is the replication steps ( with the volume to /usr/local/bin/ ) :

```
$ docker run -d --name test17-3.21 -e POSTGRES_PASSWORD=pw -v test-local-bin-99:/usr/local/bin/ -v test-db-99:/var/lib/postgresql/data postgres:17-alpine3.21
c4e4275099867b0489b1f4d39507ed22a0e3b5cfad560f446f7e872253c45a0e

$ docker stop test17-3.21
test17-3.21

$ docker run -d --name test17-3.22 -e POSTGRES_PASSWORD=pw -v test-local-bin-99:/usr/local/bin/ -v test-db-99:/var/lib/postgresql/data postgres:17-alpine3.22
def4182883216d398fb7adfb2e2d84c2420ece90983ddd3bcf31d9903daead01

$ docker logs test17-3.22

PostgreSQL Database directory appears to contain a database; Skipping initialization

Error loading shared library libicui18n.so.74: No such file or directory (needed by /usr/local/bin/postgres)
Error loading shared library libicuuc.so.74: No such file or directory (needed by /usr/local/bin/postgres)
Error relocating /usr/local/bin/postgres: ucol_getVersion_74: symbol not found
Error relocating /usr/local/bin/postgres: uloc_getLanguage_74: symbol not found
Error relocating /usr/local/bin/postgres: u_isprint_74: symbol not found
Error relocating /usr/local/bin/postgres: u_isupper_74: symbol not found
Error relocating /usr/local/bin/postgres: ucol_open_74: symbol not found
Error relocating /usr/local/bin/postgres: u_strToTitle_74: symbol not found
Error relocating /usr/local/bin/postgres: ucol_getSortKey_74: symbol not found
Error relocating /usr/local/bin/postgres: ucol_strcoll_74: symbol not found
Error relocating /usr/local/bin/postgres: ucol_close_74: symbol not found
Error relocating /usr/local/bin/postgres: uloc_getAvailable_74: symbol not found
Error relocating /usr/local/bin/postgres: ucol_nextSortKeyPart_74: symbol not found
Error relocating /usr/local/bin/postgres: uloc_countAvailable_74: symbol not found
Error relocating /usr/local/bin/postgres: u_strlen_74: symbol not found
Error relocating /usr/local/bin/postgres: u_isalpha_74: symbol not found
Error relocating /usr/local/bin/postgres: u_toupper_74: symbol not found
Error relocating /usr/local/bin/postgres: uloc_getDisplayName_74: symbol not found
Error relocating /usr/local/bin/postgres: uiter_setUTF8_74: symbol not found
Error relocating /usr/local/bin/postgres: u_isgraph_74: symbol not found
Error relocating /usr/local/bin/postgres: ucol_openRules_74: symbol not found
Error relocating /usr/local/bin/postgres: ucnv_fromUChars_74: symbol not found
Error relocating /usr/local/bin/postgres: ucol_getRules_74: symbol not found
Error relocating /usr/local/bin/postgres: ucol_strcollUTF8_74: symbol not found
Error relocating /usr/local/bin/postgres: uiter_setString_74: symbol not found
Error relocating /usr/local/bin/postgres: u_isspace_74: symbol not found
Error relocating /usr/local/bin/postgres: ucnv_toUChars_74: symbol not found
Error relocating /usr/local/bin/postgres: u_errorName_74: symbol not found
Error relocating /usr/local/bin/postgres: u_strcat_74: symbol not found
Error relocating /usr/local/bin/postgres: u_versionToString_74: symbol not found
Error relocating /usr/local/bin/postgres: ucnv_open_74: symbol not found
Error relocating /usr/local/bin/postgres: uloc_toLanguageTag_74: symbol not found
Error relocating /usr/local/bin/postgres: u_isalnum_74: symbol not found
Error relocating /usr/local/bin/postgres: u_strcpy_74: symbol not found
Error relocating /usr/local/bin/postgres: u_tolower_74: symbol not found
Error relocating /usr/local/bin/postgres: u_islower_74: symbol not found
Error relocating /usr/local/bin/postgres: u_isdigit_74: symbol not found
Error relocating /usr/local/bin/postgres: u_ispunct_74: symbol not found
Error relocating /usr/local/bin/postgres: u_strToUpper_74: symbol not found
Error relocating /usr/local/bin/postgres: u_strToLower_74: symbol not found
```
