### ISSUE TITLE
docker-composer postgres env vars

### ISSUE THREAD

**Issue by opb** [docker-library/postgres#141]
Hi all

I'm trying to bring up a postgres container with docker-compose, while setting custom `POSTGRES_*` vars.

```
version: '2'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=pony
      - POSTGRES_PASSWORD=pony
      - POSTGRES_DB=pony
    ports:
      - "5432:5432"
  web:
    image: temp-logger
    volumes:
      - .:/app
    ports:
      - "8888:5000"
    links:
      - db
    depends_on:
      - db
```

However, when I run `docker-compose --verbose up` it doesn't look like all the env vars are being passed through:

```
<snip>
compose.cli.verbose_proxy.proxy_callable: docker containers -> (list with 1 items)
compose.cli.verbose_proxy.proxy_callable: docker inspect_container <- (u'cc0aced19d4d2c0bb7205de2886792600e0a9056afa89317b1c41d4d6fa6064c')
compose.cli.verbose_proxy.proxy_callable: docker inspect_container -> {u'AppArmorProfile': u'',
 u'Args': [u'postgres'],
 u'Config': {u'AttachStderr': False,
             u'AttachStdin': False,
             u'AttachStdout': False,
             u'Cmd': [u'postgres'],
             u'Domainname': u'',
             u'Entrypoint': [u'/docker-entrypoint.sh'],
             u'Env': [u'affinity:container==cdbf6652d6a65253e798eabdd306d27c25956e59019f0911c47cac9615c08216',
                      u'POSTGRES_PASSWORD=pony',
...
</snip>
```

It looks like only the password is being set. Indeed, when I connect in from outside the docker ecosystem, I need to use `postgres` as the username, `postgres` as the db, and `pony` works as the password.

Any suggestions as to what I could be doing wrong, or is it a bug?
