### ISSUE TITLE
Change default port - Can't connect

### ISSUE THREAD

**Issue by IAPOLINARIO** [docker-library/postgres#167]
When I change the default port of the Postgres container (5432) to any other port (5433, for example), my other containers (Sonar or gitlab) can no longer communicate with the Postgres.

My docker-compose.yml file is simple just like the example below:

```
sonarqube:
  image: sonarqube
  ports:
  - "19000:9000"
  - "19092:9092"
  links:
    - sonardb
  environment:
     - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5433/sonar

sonardb:
  image: postgres:latest
  ports:
    - "5433:5432"
  environment:
    - POSTGRES_USER=sonar
    - POSTGRES_PASSWORD=sonar
```
If I just go back to the mapping "5432: 5432", the connection is normally established.
