### ISSUE TITLE
Perfect way to import backup from slave server

### ISSUE THREAD

**Issue by freeseacher** [docker-library/postgres#182]
Hi!
Can you please help me understand what is the perfect way to start developers postgres from production basebackup taken from slave server? 
Currently i can't just unzip file taken with pg_basebackup and load it image. Trouble is that i have to promote server, that cause restart and relaunch image. 
So i have so start it at least twice. I am expecting such docker-compose.yml to work

```
version: '2'
services:
  db01:
    image: "postgres:9.4"
    volumes:
      - ./db01/data:/var/lib/postgresql/data
      - ./db01/base.tar.gz:/docker-entrypoint-initdb.d/base.tar.gz
```

Or maybe there are better way to do that?
