### ISSUE TITLE
How to make persistent storage with docker-compose up-down-up?

### ISSUE THREAD

**Issue by capital-boss** [docker-library/postgres#190]
I have a multiple container application, that is using the postgres image in docker-compose.yml file. Postgres container has volume on host machine for persistent storage.

When I run `docker-compose up  ` at first time all is fine, postgres creates db files in my host folder.
After it I need to shut down application temporarily  with  `docker-compose down  ` if I'll change code of web container.

When I run    `docker-compose up  ` second time, postgres overwriting all db files, but I need that data not changes. How can I solve this issue?

**Comment by yosifkit** [comment]
If your volume is defined as `/some/local/dir/:/var/lib/postgresql/data/` then the [entrypoint script should not initialize](https://github.com/docker-library/postgres/blob/fc36c25f8ac352f1fea6d0e7cf8d9bd92a4e720f/docker-entrypoint.sh#L17) it again.

Can you share some of your postgres config in the compose yaml file?

**Comment by capital-boss** [comment]
```
version: '2'

services:
    web:
      build: ./web
      command: python3 main.py
      volumes:
        - ./web:/app
      ports:
        - "80:80"  
      depends_on:
        - db
        - redis
      links:
        - db:db
        - redis:redis
        
    db:
      image: postgres
      ports:
        - "5432:5432"     
      environment:
        - POSTGRES_PASSWORD:0000
      volumes:
        - ./pgdb:/var/lib/postgresql/data
        
    redis:
      image: redis
      ports:
        - "6379:6379" 
      command: redis-server --appendonly yes  
      volumes:
        - ./redisdb:/data

```

**Comment by capital-boss** [comment]
version: '2'

services:
    web:
      build: ./web
      command: python3 main.py
      volumes:
        - ./web:/app
      ports:
        - "80:80"  
      depends_on:
        - db
        - redis
      links:
        - db:db
        - redis:redis
        
    db:
      image: postgres
      ports:
        - "5432:5432"     
      environment:
        - POSTGRES_PASSWORD:0000
      volumes:
        - ./pgdb:/var/lib/postgresql/data
        
    redis:
      image: redis
      ports:
        - "6379:6379" 
      command: redis-server --appendonly yes  
      volumes:
        - ./redisdb:/data

**Comment by capital-boss** [comment]
```
version: '2'

services:
    web:
      build: ./web
      command: python3 main.py
      volumes:
        - ./web:/app
      ports:
        - "80:80"  
      depends_on:
        - db
        - redis
      links:
        - db:db
        - redis:redis
        
    db:
      image: postgres
      ports:
        - "5432:5432"     
      environment:
        - POSTGRES_PASSWORD:0000
      volumes:
        - ./pgdb:/var/lib/postgresql/data
        
    redis:
      image: redis
      ports:
        - "6379:6379" 
      command: redis-server --appendonly yes  
      volumes:
        - ./redisdb:/data

```
