### ISSUE TITLE
JDBC can't connect.

### ISSUE THREAD

**Issue by dessalines** [docker-library/postgres#195]
My error: `Failed to connect to JDBC URL: jdbc:postgresql://postgres:5432/MY_DB`

Not sure what the `jdbc.url` is supposed to be, whether it should be `postgres`, or `127.0.0.1`, or what.

My `docker-compose.yml`
```yaml
version: '2'
services:
  db:
    image: postgres:9.3
    restart: always
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: postgres
      POSTGRES_DB: MY_DB
  web:
    build: .
    ports: 
      - "4567:4567"
    links:
      - db
    depends_on:
      - db
    volumes:
      - .:/services/target
      - .:/ui/dist
```
