### ISSUE TITLE
Correct way to change tcp_keepalives settings

### ISSUE THREAD

**Issue by kampta** [docker-library/postgres#198]
I want to change the following parameters of postgres config, `tcp_keepalives_count`,  `tcp_keepalives_idle`, ` tcp_keepalives_interval`.

What is the recommended way to change them?

Following is my `docker-compose.yml`

```
postgres:
  restart: always
  image: postgres:latest
  volumes:
    - /data:/var/lib/postgresql
  ports:
    - "5432:5432"
  environment:
    - POSTGRES_USER=admin
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=postgres
```
