### ISSUE TITLE
Postgres 9.6.1-alpine - FATAL: no PostgreSQL user name specified in startup packet

### ISSUE THREAD

**Issue by UbikZ** [docker-library/postgres#259]
Hi there,

I have an issue when I try to launch my container :
```pgsql_1     | FATAL:  no PostgreSQL user name specified in startup packet```

My **docker-compose.yml** is pretty simple : 
```yml
jscraper:
  build: jscraper
  links:
    - redis
    - pgsql
  ports:
      - "3000:3000"
  volumes:
      - /srv/docker/jscraper/scraper/log:/var/log
  env_file: .env
pgsql:
  image: postgres:9.6.1-alpine
  ports:
    - "5432:5432"
  volumes:
    - /srv/docker/jscraper/pgsql/data:/var/lib/postgresql/data
  env_file: .env
redis:
  build: redis
  ports:
      - "6379:6379"
  volumes:
      - /srv/docker/jscraper/redis/data:/data
  env_file: .env
```

My **.env** environment file :
```
POSTGRES_DB=scraper
POSTGRES_USER=scraper
POSTGRES_PASSWORD=scraper
REDIS_PASSWORD=scraper
```

I don't really understand that error. I don't find relevant stuff on google about that with the docker & alpine context.

Thank's for your answers.

UbikZ.
