### ISSUE TITLE
Altough the home directory of postgres user is /var/lib/postgresql, the owner is root.

### ISSUE THREAD

**Issue by edib** [docker-library/postgres#274]
I am getting an error "could not save history to file "/var/lib/postgresql/.psql_history": Permission denied" in alpine version.

**Comment by yosifkit** [comment]
Ah, the `/var/lib/postgresql/` directory is created by the installer in Debian.  Looks like we need to `chown` it in the Dockerfile.

```console
$ docker run -it --rm postgres:alpine bash
bash-4.3# ls -la $PGDATA
total 8
drwxrwxrwx    2 postgres postgres      4096 Apr 12 18:10 .
drwxr-xr-x    3 root     root          4096 Apr  7 17:46 ..
bash-4.3# echo $PGDATA
/var/lib/postgresql/data
bash-4.3# exit
$ docker run -it --rm postgres bash
root@fd5dfbc8c064:/# ls -la $PGDATA
total 8
drwxrwxrwx 2 postgres postgres 4096 Apr 12 18:11 .
drwxr-xr-x 3 postgres postgres 4096 Apr  7 17:45 ..
root@fd5dfbc8c064:/# echo $PGDATA
/var/lib/postgresql/data
```

**Comment by dkadioglu** [comment]
I have this issue again with v18. I started over with a fresh container and newly created volumes. This is my compose file:
```
services:

  db:
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=redacted
      - TZ=Europe/Berlin
      - PGTZ=Europe/Berlin
    volumes:
      - /mnt/storage/postgres-data:/var/lib/postgresql
    ports:
      - "5432:5432"
```
