### ISSUE TITLE
unable to extend the image

### ISSUE THREAD

**Issue by edwards33** [docker-library/postgres#333]
I am using a dockercompose:
* content of docker-compose.yml:
````
version: "3.1"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile2.txt
    links:
      - postgres
    depends_on:
      - postgres
    ports:
      - "2939:22"
      - "3333:3333"

  postgres:
    build:
          context: .
          dockerfile: Postgresfile3.txt
          args:
            POSTGRES_PASSWORD: #####
````
* content of dockerfile: Postgresfile3.txt:
````
FROM postgres:alpine

COPY initUserDb.sh /docker-entrypoint-initdb.d/initUserDb.sh
RUN chmod 755 /docker-entrypoint-initdb.d/initUserDb.sh
````
* content of initUserDb.sh:
````
#!/bin/sh
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL    
    CREATE USER docker;
    CREATE DATABASE docker;
    GRANT ALL PRIVILEGES ON DATABASE docker TO docker;  
EOSQL
````
* run "docker-compose up" command

output:
````
...
postgres_1  | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/initUserDb.sh                    
" does not existTAL:  database "                                                                                        
" does not existql: FATAL:  database "                                                                                  
postgres_postgres_1 exited with code 2 

````
What is the real meaning of:
````
does not existTAL:
does not existql:
````

Thanks
