### ISSUE TITLE
sh: locale: not found

### ISSUE THREAD

**Issue by bkuhl** [docker-library/postgres#337]
I have the `9.6-alpine` container running (I've also tried just using `9.6`) and am running into a locale issue.  

**Kubernetes Configuration**

```
      - name: postgres
        image: postgres:9.6-alpine
        imagePullPolicy: IfNotPresent
        env:
          - { name: "POSTGRES_DB", value: "app_db" }
          - { name: "POSTGRES_USER", value: "db_user" }
          - { name: "POSTGRES_PASSWORD", valueFrom: { secretKeyRef: { name: laravel-starter-secrets, key: db.password }} }
```

**Container Output**

```
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.
 The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".
 Data page checksums are disabled.
 fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... No usable system locales were found.
Use the option "--debug" to see details.
sh: locale: not found
ok
 WARNING: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.
syncing data to disk ... ok
 Success. You can now start the database server using:
     pg_ctl -D /var/lib/postgresql/data -l logfile start
 waiting for server to start....LOG:  database system was shut down at 2017-09-13 14:17:11 UTC
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
 done
server started
CREATE DATABASE
 CREATE ROLE
 /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
 waiting for server to shut down....LOG:  received fast shutdown request
LOG:  aborting any active transactions
LOG:  autovacuum launcher shutting down
LOG:  shutting down
```

I'm unsure how to pass `--debug` given the initialization script in this container.  How can I debug what's happening here?  My assumption is that the `locale` issue is preventing the container from running since I don't see any other issues in this output.
