### ISSUE TITLE
Volume mount from ntfs mounted drive gives permission denied for init scripts

### ISSUE THREAD

**Issue by ashic** [docker-library/postgres#338]
I have a docker-compose file 

```
version: "3"
services:
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pass1234
      POSTGRES_USER: filtro
      POSTGRES_DB: filtroui
    volumes:
      - ./src/resources/db_schema/:/docker-entrypoint-initdb.d/
```

If I run this from an NTFS volume mounted in Linux, it gives permission denied when trying to execute the first sql file in the db_schema directory. (The directory belonging to 46 plugdev). If I copy the code to an ext volume and run it, it runs fine. If I change volumes to be:

```
    volumes:
      - ./src/resources/db_schema/0_db.sql:/docker-entrypoint-initdb.d/0_db.sql
      - ./src/resources/db_schema/1_indexes.sql:/docker-entrypoint-initdb.d/0_indexes.sql

```
i.e. list out each file individually, then it runs fine from the NTFS mounted volume.
