### ISSUE TITLE
Initial schema setup file not being ran

### ISSUE THREAD

**Issue by Syntaf** [docker-library/postgres#345]
Excuse my lack of knowledge with docker, but I can't seem to figure out why my initial schema isn't being ran. My docker-compose looks like:

```
version: '2'

services:
    boilerplatebackend:
        ...

        depends_on:
            - postgres

        environment:
            DATABASE_URL: ...

        ports:
          - "8080:8080"
    postgres:
        image: postgres
        environment:
            POSTGRES_USER: smashggextadmin
            POSTGRES_DB: smashggext
        build: ./backend/database
```

then inside `./backend/database` I have

```
FROM postgres
COPY ./initial_schema.sql /docker-entrypoint-initdb.d/
```

where initial_schema.sql =
`CREATE TABLE links(channelid INT NOT NULL PRIMARY KEY, link VARCHAR(255) NOT NULL)`

Everything seems to get up and running, but the links table is never created. Am I doing something blatantly wrong here? Thanks a bunch for any help!
