### ISSUE TITLE
connection issues

### ISSUE THREAD

**Issue by SiddiquiImran** [docker-library/postgres#377]
Hi All,
I am new in docker as well as postgres, as per requirement I am exploring these new areas and i am happy to learn.
but i got stuck in between, I followed this video to setup and test;
https://www.youtube.com/watch?v=edPrPcgjTgw

docker compose yml file content is:
```yaml
version: '3'
services:
  api:
    container_name: api
    build: ./api/
    links:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:sa123@db:5432/koa_api
    command: npm start
    ports:
      - '3000:3000'
    volumes:
      - ./api:/web
  db:
    image: postgres:10
    container_name: db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sa123
      - POSTGRES_DB=koa_api
```
I have installed postgres datbas ein my local machine(Windows 10) and have create one database which is running in port no 5432 so if i keep same port for external database  and one in containr it gives me this error:

![image](https://user-images.githubusercontent.com/20870175/33204762-93e6d962-d12a-11e7-89a5-f618580b12d4.png)

And if i change my Windows 10 postgres server port to 5431 then it gives that error and yaml for the same is:

```yaml
version: '3'
services:
  api:
    container_name: api
    build: ./api/
    links:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:sa123@db:5432/koa_api
    command: npm start
    ports:
      - '3000:3000'
    volumes:
      - ./api:/web
  db:
    image: postgres:10
    container_name: db
    ports:
      - '5431:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sa123
      - POSTGRES_DB=koa_api
```

Error:

![image](https://user-images.githubusercontent.com/20870175/33206853-9a7aabf8-d131-11e7-8f54-76dfaa82edaa.png)
