### ISSUE TITLE
[Question] what is the recommended way to restore a backup in a docker-compose environment?

### ISSUE THREAD

**Issue by wotanii** [docker-library/postgres#388]
I'm working on backup-sidecar, that makes it as easy as possible to handle backups. 

The creating of the backups is simple enough: it's just a script, that calls "pg_dumpall" every now and then. But the restoring of the backup is a little more complicated. Especially since all clients need to be disconnected during the restore. 

A script running on the host would have to know the exact names of the services, the current state of the services and the relevant env-vars. I believe this would be hard to do automatically, and it would also be outdated very fast. That's why I want to solve this via a docker-container.

### Question

* What is the recommended way to restore a backup, when postgres run with docker-compose? 

follow up questions: 

* How do other people deal with this problem? 
* Is it possible for my sidecar to shut down postgres, when the backup is restored? (that way the admin wouldn't have to press `ctrl+c`, and the whole process could be scripted easily)

### my solution so far

I want the solution to be as generic as possible. The admin shouldn't even have to know, that the backup is being restored to a psql database. In the future I want to set up a similar restore-strategy for our other databases, so admins can use the same emergency procedure for all services. 

I have come up with a _docker-compose-restore.yml_, that looks somewhat like this: 
```
services:
  web:
    restart: "no"
    command: "echo 'web disabled'"

  backup:
    restart: "no"
    command: >
      bash -c "while ! nc -w 1 -z db 5432; do sleep 0.1; echo 'waiting for db...'; done;
      sleep 2 &&
      /src/restore.py"
    environment:
      - BACKUP=/dump.sql
    volumes:
      - ${BACKUP}:/dump.sql

  db:
    restart: "no"
```

So when a backup needs to be restored, the admins do this: 

```
docker-compose down
BACKUP="/path/to/the/backup.sql" docker-compose -f docker-compose-restore.yml up
# ... wait a little ...
# ctrl + c
docker-compose up -d
```
