### ISSUE TITLE
docker-entrypoint-initdb.d doesn't executes the postgis.sh script

### ISSUE THREAD

**Issue by slim-hmidi** [docker-library/postgres#411]
I'm trying to create a postgis extension. 
Dockerfile:
```
FROM postgres:9.6.4

RUN apt-get clean \
    && apt-get update \
    && apt-get -y install postgis \
    && rm -rf /var/lib/apt/lists/*

COPY ./scripts/postgis.sh  /docker-entrypoint-initdb.d/postgis.sh
RUN chmod +x /docker-entrypoint-initdb.d/postgis.sh
```
postgis.sh:
```
#!/bin/bash -x
for DB in $(psql -U backend -t -c  "SELECT datname from pg_database where datname = 'backend'"); do
    echo "Loading PostGIS extensions into $DB"
    psql -U backend -d $DB -c "CREATE EXTENSION IF NOT EXISTS postgis"
done
```

backend.yaml:
```
apiVersion: v1
kind: Service
metadata:
  name: backend-db
  labels:
    app: backend-db
  namespace: default
spec:
  selector:
    app: backend-db
  ports:
  - name: http
    port: 5432
    targetPort: http-postgres
    nodePort: 30100
  type: NodePort

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: backend-db-config
  namespace: default
data:
  postgres_user: backend
  postgres_password: backend

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend-db
  labels:
    app: backend-db
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend-db
    spec:
      containers:
      - name: backend-db
        image: user/postgres-db
        imagePullPolicy: IfNotPresent
        env:
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: backend-db-config
              key: postgres_user
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: backend-db-config
              key: postgres_password
        ports:
        - name: http-postgres
          containerPort: 5432
        volumeMounts:
        - name: vm-backend-db
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: vm-backend-db
        hostPath:
          path: /data/vm-backend-db
```

I check the database, it runs well but the extension did not exist. How can I fix that?
