### ISSUE TITLE
Not able to connect to both postgres instances running as container trough host ( localhost )

### ISSUE THREAD

**Issue by harishajdarevic** [docker-library/postgres#425]
Hello,

I do a lot of research but still not able to find how to fix this.

My image look like this:

```
  pgsql:
    image: postgres:10.1
    container_name: "first-pgsql"
    environment:
      - 'DB_USER=${DB_USER}'
      - 'DB_PASS=${DB_PASS}'
    volumes:
      - '${DB_VOLUME_LOCATION}:/var/lib/postgresql/data'
    ports:
      - 5432:5432
    restart: 'always'
```

And when I do `docker-compose up  -d` and `docker ps`

I get results for column PORTS as:

`0.0.0.0:5432->5432/tcp ` and that is good because I'm able to connect to this database from host machine using localhost:5432

Now I'm adding a new container in paraller with this configuration:

```
  pgsql2:
    image: postgres:10.1
    container_name: "second-pgsql"
    environment:
      - 'DB_USER=${DB_USER}'
      - 'DB_PASS=${DB_PASS}'
    volumes:
      - '${DB_VOLUME_LOCATION}:/var/lib/postgresql/data'
    ports:
      - 6666:6666
    restart: 'always'
```

As you can see above port is changed to 6666. 

Now I am getting results for column PORTS as:

`5432/tcp, 0.0.0.0:6666->6666/tcp` and that is not good because I'm not able to connect to another instance of postgres from my host using localhost:6666

It seems how it works very well only for default pg port 5432 when we come to connecting on host machine to postgres container instance. For any other port it doesn't work.
