### ISSUE TITLE
Problem with connection to postgres from outside

### ISSUE THREAD

**Issue by forestyura** [docker-library/postgres#430]
I try to run postgres image with docker compose and connect from outside

compose: 

```
version: "3.1"
services:
  postgres_db:
    image: postgres:9.6
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=test
    ports:
      - "5432:5432"
```

On mac when try to connect to test (with user test and password 123456) i have message 'incorrect password', but when connect to postgres (with user postgres and password postgres) i can connect - 

If i try to connect on Windows i have 'connection refused'.  on compose file what i run on windows i don't have that field: 
volumes:
      - ./postgres:/var/lib/postgresql/data
