### ISSUE TITLE
Windows 10 is always FATAL:  data directory "/var/lib/postgresql/data" has wrong ownership

### ISSUE THREAD

**Issue by blacksourcez** [docker-library/postgres#435]
On Windows 10 Pro is always failed while docker-compose up, otherwise on mac is work perfectly.

Here are some my docker-compose file:

```yml
version: '2'
services:
.
.
.
.
  postgresql:
    image: postgres:93
    container_name: lemp-postgresql
    restart: always
    environment:
      POSTGRES_PASSWORD: asdf
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
      - ./postgresql/conf:/etc/postgresql/
    ports:
      - "5432:5432"
    networks:
      lemp-network:
        ipv4_address: ${LEMP_POSTGRES_IP}

networks:
  lemp-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${LEMP_SUBNET}
          gateway: ${LEMP_GATEWAY}
```

and there are some logs.

```
lemp-postgresql | FATAL:  data directory "/var/lib/postgresql/data" has wrong ownership
lemp-postgresql | HINT:  The server must be started by the user that owns the data directory.
lemp-postgresql exited with code 1
lemp-postgresql | FATAL:  data directory "/var/lib/postgresql/data" has wrong ownership
lemp-postgresql | HINT:  The server must be started by the user that owns the data directory.
lemp-postgresql | FATAL:  data directory "/var/lib/postgresql/data" has wrong ownership
lemp-postgresql | HINT:  The server must be started by the user that owns the data directory.
lemp-postgresql | FATAL:  data directory "/var/lib/postgresql/data" has wrong ownership
lemp-postgresql | HINT:  The server must be started by the user that owns the data directory.
lemp-postgresql exited with code 1
lemp-postgresql | FATAL:  data directory "/var/lib/postgresql/data" has wrong ownership
lemp-postgresql | HINT:  The server must be started by the user that owns the data directory.
lemp-postgresql | FATAL:  data directory "/var/lib/postgresql/data" has wrong ownership
lemp-postgresql | HINT:  The server must be started by the user that owns the data directory.
lemp-postgresql | FATAL:  data directory "/var/lib/postgresql/data" has wrong ownership
lemp-postgresql | HINT:  The server must be started by the user that owns the data directory.
lemp-postgresql | FATAL:  data directory "/var/lib/postgresql/data" has wrong ownership
lemp-postgresql | HINT:  The server must be started by the user that owns the data directory.
lemp-postgresql | FATAL:  data directory "/var/lib/postgresql/data" has wrong ownership
lemp-postgresql | HINT:  The server must be started by the user that owns the data directory.
lemp-postgresql exited with code 1
```

**Comment by maiorano84** [comment]
I have this same issue only on Windows. Everywhere else is fine.

The only way I was able to get around this was through a named volume mount:

    postgresql:
      image: postgres:93
      volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgresql/conf:/etc/postgresql/
    ...
    volumes:
      postgres:

**Comment by tianon** [comment]
Unfortunately, this is likely https://github.com/docker/for-win/issues/445, and there's not really anything we can do to fix it directly in the image.  You might be able to work around it by messing with `--user` (`user:` in the compose YAML), but there are some caveats to that noted in https://hub.docker.com/_/postgres/.

**Comment by matthewfieger** [comment]
Are there any updates on this issue?  Here is a simple case to produce this error:

Compose file:
```
version: "3.7"
services:
  postgres-test:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./postgres/data:/var/lib/postgresql/data/pgdata
```

Docker file:
```
FROM postgres:11.5-alpine
RUN mkdir -p "$PGDATA" && chmod -R 700 "$PGDATA" && chown -R postgres:postgres "$PGDATA"
```

I tried 1) changing the location of the data folder 2) running as root and 3) changing the ownership of the data folder.  I can't use a named volume as others have suggested because I need to mount the data folder to a specific location on my server.

**Comment by yami12376** [comment]
I have the same issue running:
```docker run --name some-postgres -v E:\tmp\postgresBaza:/var/lib/postgresql/data -d postgres:9.6.15```

I get from logs:

> FATAL:  data directory "/var/lib/postgresql/data" has wrong ownership

**Comment by sieestaa** [comment]
Win10


version: '3.7'

services:
  db:
    image: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: spone
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432


 running bootstrap script ... 2019-12-14 16:22:31.815 UTC [80] FATAL:  data directory "/var/lib/postgresql/data" has wrong ownership

**Comment by sieestaa** [comment]
I solved it!

```
version: '3.7'


services:
  db:
    image: postgres
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myusername
      POSTGRES_PASSWORD: 123456
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local
```


BUT environment doesn`t work, use default
u can check on adminer - localhost:8080
user: **postgres**
password: **postgres**

**Comment by netsrotr** [comment]
Maybe there is a way to get around this using the [userns-remap](https://docs.docker.com/engine/security/userns-remap/#enable-userns-remap-on-the-daemon) on the deamon? Must the docker image be "prepared" to use that feature?

**Comment by reinierkors** [comment]
I solved this by mapping my local volume one directory below the one Postgres needs:

```
version: '3'
services:
  postgres:
    image: postgres
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql
    ports:
      - 5432:5432
```

**Comment by PaulMEdwards** [comment]
This solution worked for me:

https://github.com/docker/for-win/issues/445#issuecomment-605572838

**Comment by hgoo150925** [comment]
> I solved this by mapping my local volume one directory below the one Postgres needs:
> 
> ```
> version: '3'
> services:
>   postgres:
>     image: postgres
>     restart: on-failure
>     environment:
>       - POSTGRES_USER=postgres
>       - POSTGRES_PASSWORD=password
>       - PGDATA=/var/lib/postgresql/data/pgdata
>       - POSTGRES_DB=postgres
>     volumes:
>       - ./postgres_data:/var/lib/postgresql
>     ports:
>       - 5432:5432
> ```

Thank U!! I solve my problem

**Comment by Fincentxyz** [comment]
Any updates on this issue? I'm trying to deploy a Postgresql Docker container in Microsoft Azure. Their YAML file doesn't have the ability to use named volumes as far as I can tell. When I'm using azureFile, which is basically a bind mount, I stumble upon this issue as well...

**Comment by riclovato** [comment]
> I solved this by mapping my local volume one directory below the one Postgres needs:
> 
> ```
> version: '3'
> services:
>   postgres:
>     image: postgres
>     restart: on-failure
>     environment:
>       - POSTGRES_USER=postgres
>       - POSTGRES_PASSWORD=password
>       - PGDATA=/var/lib/postgresql/data/pgdata
>       - POSTGRES_DB=postgres
>     volumes:
>       - ./postgres_data:/var/lib/postgresql
>     ports:
>       - 5432:5432
> ```

it worked for me. Thank you!

**Comment by Trolldemorted** [comment]
@reinierkors your solution works only if you have docker desktop installed (opposed to just using docker in WSL2), right?

I just tested it (WSL2, folder is in `/mnt/c/`, no docker desktop) and it doesn't work:
```yaml
services:
  postgres18:
    image: postgres:18
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "./data/postgres18:/var/lib/postgresql/"
```

Postgres is noping out immediately:
```
postgres18-1  | chmod: changing permissions of '/var/lib/postgresql/data/pgdata': Operation not permitted
postgres18-1  | The files belonging to this database system will be owned by user "postgres".
postgres18-1  | This user must also own the server process.
postgres18-1  |
postgres18-1  | The database cluster will be initialized with locale "en_US.utf8".
postgres18-1  | The default database encoding has accordingly been set to "UTF8".
postgres18-1  | The default text search configuration will be set to "english".
postgres18-1  |
postgres18-1  | Data page checksums are enabled.
postgres18-1  |
postgres18-1  | initdb: error: could not change permissions of directory "/var/lib/postgresql/data/pgdata": Operation not permitted
```
