### ISSUE TITLE
POSTGRES_USER and POSTGRES_DB is not working

### ISSUE THREAD

**Issue by tom10271** [docker-library/postgres#459]
`docker-compose.yml`

```yml
version: '2.2'
services:
  postgres:
    image: postgres:9.6.9
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=pwd
    ports:
      - 8964:5432
```

I can only connect to DB by `127.0.0.1:8964` with 
```
username: postgres
pwd: pwd
database name: postgres
```
