### ISSUE TITLE
Running initial commands with psql

### ISSUE THREAD

**Issue by GVSO** [docker-library/postgres#460]
I'm trying to run initial commands and load initial data into postgres, but I keep getting an error that is apparently related to the socket

```
psql: could not connect to server: No such file or directory
        Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"
```

This is my _docker-compose.yml_

```
version: '3'

services:
  node:
    container_name: container1
    image: image1
    build:
      context: .
      dockerfile: "node.dev.dockerfile"
    ports:
      - "4000:4000"
    working_dir: "/var/app"
  
  postgres:
    container_name: container2
    image: image2
    build:
      context: .
      dockerfile: "postgres.dev.dockerfile"
    ports:
      - "5432:5432"
```

**postgres.dev.dockerfile**

```
FROM postgres:10

ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD postgres
ENV POSTGRES_DB postgres

COPY ./postgres_scripts/initialize.sh /usr/local/bin/

RUN initialize.sh
```

**initialize.sh**
```
#!/bin/bash
set -e

psql --username "$POSTGRES_USER" --dbname "$POSTGRES_DB"
...
```
