### ISSUE TITLE
SSL Recommendation? 

### ISSUE THREAD

**Issue by MaerF0x0** [docker-library/postgres#473]
I'm wanting to run a PG container for tests, and because we use SSL in production, I'd like to run with SSL enabled container in our CI. 

Is there a recommended way to run with SSL? 
I wonder if it's worth adding a tag set like   `<version>-ssl`  ? 

I can probably muster a PR if welcomed.

**Comment by wglambert** [comment]
We don't have anything in the docs about it, I found [this](https://markwoodbridge.com/2017/08/16/postgres-docker-ssl.html) but haven't tested it

**Comment by tianon** [comment]
There's definitely not anything we should adjust in the image here (since it's as trivial as dropping in two key files and setting `ssl=on` which can be done trivially via the container command), and I think it might even be overkill to add to the docs, especially since https://markwoodbridge.com/2017/08/16/postgres-docker-ssl.html is a decently high Google result for "postgresql docker ssl" (in fact, top result for me).

**Comment by MaerF0x0** [comment]
So my thoughts stem more from the benefits of having a commonly available image for SSL to encourage testing with ssl. When a common image is available, all consumers benefit because image caches in CI platforms (say circleCI ) can be warm.  Kind of a similar concept to using a CDN for common JavaScript libraries. 

Maybe I'll just maintain my own set to see if others find value.

**Comment by tianon** [comment]
I guess what I'm confused about is the image you're talking about.  There are two things required for enabling SSL, and they're both pretty trivial:

1. add certificates to the running container (easy to do via bind mount; would be needed for a client to connect anyhow)

2. add `ssl=on` to the running configuration (trivial to do via `-c ssl=on` as the "command" to this image)

So, a simple YAML file for doing so could look something like this:

```yaml
db:
  image: postgres:10
  command: -c ssl=on
  volumes:
    - ./server.crt:/var/lib/postgresql/data/server.crt
    - ./server.key:/var/lib/postgresql/data/server.key
```

**Comment by MaerF0x0** [comment]
To continue the circleci example: https://circleci.com/docs/2.0/building-docker-images/ 

When you want to run a dependency container you only get to specify the image. But I can see that we could try something like (untested):

```yaml
 steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Postgres
          command: |
            # create a dummy container which will hold a volume with config
           docker create --name pg postgres:10 /bin/true
           # copy certs into this container
           docker cp test/server.* pg:/var/lib/postgresql/data/  
           docker run pg 'postgres -c ssl=on'
```

**Comment by tianon** [comment]
Are you sure?  From what I can see in https://circleci.com/docs/2.0/configuration-reference/#docker--machine--macosexecutor, it seems you can list multiple containers and each one can have a separate `command:`, `environment:`, etc?

**Comment by MaerF0x0** [comment]
^^ Good find, i was looking for those options when I wrote my response. Unfortunately I think volume isnt an option, so still need to get the certs into the container.

So maybe this would work: 
```yaml
jobs:
  tests:
    docker:
      - image: postgres:10
        name: pg
        command: -c ssl=on
    steps:
       - run: docker cp test/server.* pg:/var/lib/postgresql/data/  
       - run: docker exec pg '/etc/init.d/postgresql restart'
```
