### ISSUE TITLE
Port redirection does not work

### ISSUE THREAD

**Issue by AndersonDan** [docker-library/postgres#525]
Hello, I'm using Docker for Windows. And I have a file docker-compose.yml where it has several services, where the "ports" configuration works for everyone, except for postgres. I found a solution looking at some issues.

It does NOT work:
```
database:
    container_name: my-awesome-project-database
    build:
        context: ./
        dockerfile: ./build/db/Dockerfile
    restart: always
    ports:
      - '885:5432'
    environment:
      POSTGRES_USER: my-awesome-project
      POSTGRES_PASSWORD: my-awesome-project
      POSTGRES_DB: my-awesome-project
    volumes:
      - database-data:/var/lib/postgresql/data
```

This always results in something like:

`could not connect to server: Connection refused my-awesome-project-app   |    Is the server running on host` `my-awesome-project-database (172.22.0.3) and accepting my-awesome-project-app     |    TCP/IP connections on port 885?`

But this works:

```
database:
    container_name: my-awesome-project-database
    build:
        context: ./
        dockerfile: ./build/db/Dockerfile
    restart: always
    environment:
      POSTGRES_USER: my-awesome-project
      POSTGRES_PASSWORD: my-awesome-project
      POSTGRES_DB: my-awesome-project
    volumes:
      - database-data:/var/lib/postgresql/data
    command: -p 885
```

Windows 10 Pro 10.0.17763.55
Docker version 18.06.1-ce, build e68fc7a
docker-compose version 1.22.0, build f46880fe
Version of Postgres: 10.6
