### ISSUE TITLE
Shutting down postgres gracefully with docker-compose down to avoid recovery process

### ISSUE THREAD

**Issue by cherner** [docker-library/postgres#544]
Sometimes when I shutdown postgres (v9.4.20) with `docker-compose down` (v1.23.2) , the next time that I run `docker-compose up`, postgres claims `database system was not properly shut down; automatic recovery in progress` and takes forever to start back up. Even though when I shut it down the postgres logs say `received smart shutdown request`. Even trying with `docker-compose down -v` does not seem to resolve the issue. Here's my `docker-compose.yml` file.

```yml
version: "3.5"
networks:
  network1:
    driver: bridge
    name: sharedservices

services:

  postgres:
    image: postgres:9.4
    volumes:
      - "${PG_CONF_FILE}:/conf/postgresql.conf"
      - "${PG_DATA_DIR}:/var/lib/postgresql/data"
      - "${PG_HBA_FILE}:/conf/pg_hba.conf"
      - "${PG_LOG_DIR}:/logs"
    ports:
      - "${PG_PORT}:5432"
    expose:
      - "5432"
    networks:
      - network1
    environment:
      TZ: America/Chicago
    command: postgres -c log_directory=/logs -c config_file=/conf/postgresql.conf -c hba_file=/conf/pg_hba.conf
```

Any ideas on how to avoid an "automatic recovery" ?
