### ISSUE TITLE
sql files not getting executed under docker-entrypoint-initdb.d

### ISSUE THREAD

**Issue by weizhang9** [docker-library/postgres#562]
Hello

I tried searching the related closed issues but couldn't seem to find a solution to the issue as described in the title.  
My `docker-compose.yml` is as follows:
```
version: '3'
services:
  db:
    image: postgres
    container_name: postgresapi
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: postgres-dev
      POSTGRES_PASSWORD: s3cr3tp4ssw0rd
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql
      - ./tb-queries:/docker-entrypoint-initdb.d
      - ./data:/var/lib/postgresql/data

  app:
    build: .
    command: ["./wait-for-it.sh", "db:5432"]
    volumes:
      - .:/go/src/app
    ports:
      - "80:8080"
    depends_on:
      - db
      - redis
    links:
      - db
      - redis

  redis:
    image: redis
```
  

After running `docker-compose up` the postgres relevant logs are:

```
postgresapi | 2019-03-25 23:41:31.992 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgresapi | 2019-03-25 23:41:31.992 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgresapi | 2019-03-25 23:41:31.995 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgresapi | 2019-03-25 23:41:32.012 UTC [23] LOG:  database system was interrupted; last known up at 2019-03-25 23:25:46 UTC
postgresapi | 2019-03-25 23:41:32.142 UTC [23] LOG:  database system was not properly shut down; automatic recovery in progress
postgresapi | 2019-03-25 23:41:32.143 UTC [23] LOG:  redo starts at 0/1650988
postgresapi | 2019-03-25 23:41:32.143 UTC [23] LOG:  invalid record length at 0/1650A68: wanted 24, got 0
postgresapi | 2019-03-25 23:41:32.143 UTC [23] LOG:  redo done at 0/1650A30
postgresapi | 2019-03-25 23:41:32.156 UTC [1] LOG:  database system is ready to accept connections
postgresapi | 2019-03-25 23:41:32.759 UTC [30] LOG:  incomplete startup packet
postgresapi | 2019-03-25 23:42:10.193 UTC [31] LOG:  incomplete startup packet
```

I didn't see `initdb` nor copy of entry point volumes get executed in the log. And I connected to the server through pgAdmin4 and didn't see the tables that were supposed to get created from the sql files under entry point. Please could you point me into the right direction? I am totally new to postgres, just trying to learn. Any help/suggestions will be greatly appreciated.

Many thanks in advance!
