### ISSUE TITLE
initdb: could not change permissions of directory "/var/lib/postgresql/data": Operation not permitted

### ISSUE THREAD

**Issue by lluck42** [docker-library/postgres#563]
window 10 hyperv
use minikube

```yml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:11.2-alpine
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-data
        env:
        - name: POSTGRES_PASSWORD
          value: a.123456
      volumes:
        - name: postgres-data
          hostPath:
            path: /f/postgres/data
```
result:
```console
initdb: could not change permissions of directory "/var/lib/postgresql/data": Operation not permitted
fixing permissions on existing directory /var/lib/postgresql/data ...
```
