### ISSUE TITLE
My data lost after removing the container

### ISSUE THREAD

**Issue by pavelkeyzik** [docker-library/postgres#569]
Hi! Can you help me fix some problem with my database?

I have a `docker-compose.yml` with some configuration. It works correctly but after removing my container and start again I lose my data in the database. What am I doing wrong?

OS: Windows 10
Configuration file:
```
db:
    image: postgres:11.1
    restart: always
    ports:
      - 5444:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
    volumes:
      - pgdata:/var/lib/postgresql/data
```

**Comment by wglambert** [comment]
How did you stop/remove the container? Using your compose file works fine and the data in `pgdata` will persist

```console
$ docker-compose up -d
Creating postgres-569_db_1_2b2b84bc0b0b ... done

$ docker exec -it postgres-569_db_1_77f2c575049a psql -Upostgres
psql (11.1 (Debian 11.1-3.pgdg90+1))
Type "help" for help.

postgres=# create database mydb;
CREATE DATABASE

postgres=# exit

$ docker-compose down
Stopping postgres-569_db_1_77f2c575049a ... done
Removing postgres-569_db_1_77f2c575049a ... done

$ docker-compose up -d
Creating postgres-569_db_1_51d9eb4008c9 ... done

 docker exec -it postgres-569_db_1_65e1faefff2e psql -Upostgres
psql (11.1 (Debian 11.1-3.pgdg90+1))
Type "help" for help.

postgres=# \l
                                 List of databases
   Name    |  Owner   | Encoding |  Collate   |   Ctype    |   Access privileges
   
-----------+----------+----------+------------+------------+--------------------
---
 mydb      | postgres | UTF8     | en_US.utf8 | en_US.utf8 | 
 postgres  | postgres | UTF8     | en_US.utf8 | en_US.utf8 | 
 template0 | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres        
  +
           |          |          |            |            | postgres=CTc/postgr
es
 template1 | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres        
  +
           |          |          |            |            | postgres=CTc/postgr
es
 test      | postgres | UTF8     | en_US.utf8 | en_US.utf8 | 
(5 rows)
```

**Comment by pavelkeyzik** [comment]
What if I'll remove a container with `docker rm [container]`? Without removing my volume.

**Comment by wglambert** [comment]
That wouldn't delete the contents of any volumes and your volume should still show up under `docker volume ls`

**Comment by fayad** [comment]
I think your dockercompose is missing an additional definition for the volume.

```
db:
    image: postgres:11.1
    restart: always
    ports:
      - 5444:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
```
For the record this way data persists even with `docker rm` unless you do a volume remove with `docker rm -v`
