### ISSUE TITLE
Cannot set timezone

### ISSUE THREAD

**Issue by nusendra** [docker-library/postgres#574]
Here is my compose file

```
version: '3'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=blabla
      - POSTGRES_PASSWORD=blabla
      - POSTGRES_DB=blabla
      - TZ=Asia/Jakarta
```

But when I login to db with pgadmin, and make a query `show timezone`. It still in UTC, not 'Asia/Jakarta'

How to fix this?
