### ISSUE TITLE
Postgres process sometime listen on localhost instead of 0.0.0.0

### ISSUE THREAD

**Issue by pckhoi** [docker-library/postgres#583]
I run a custom postgres image with docker-compose and sometime I cannot connect to it, and it is always because Postgres process somehow bound to `127.0.0.1:5432` instead of `0.0.0.0:5432`. It is driving me nut because sometime it bind correctly to `0.0.0.0` sometime it bind to `127.0.0.1` instead:
```
postgres_1    | 2019-05-22 03:20:13.657 GMT [1] LOG:  listening on IPv4 address "127.0.0.1", port 5432
postgres_1    | 2019-05-22 03:20:13.662 GMT [1] LOG:  could not bind IPv6 address "::1": Address not available
postgres_1    | 2019-05-22 03:20:13.662 GMT [1] HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
```

Below is my docker-compose config:

```
  postgres:
    build:
      context: ./postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=wrgl
      - POSTGRES_PASSWORD=password
```

My custom postgres image only has an additional script to change a couple lines in postgresql.conf.

Docker context:
```
postgres
    |_  Dockerfile
    |_  enable_log_statement.sh
```
Dockerfile:
```
FROM postgres:11.3-alpine

ADD . /docker-entrypoint-initdb.d
```
enable_log_statement.sh:
```
#!/bin/sh
set -x

PGCONF=/var/lib/postgresql/data/postgresql.conf
cat $PGCONF | sed "s/#log_statement = 'none'.*/log_statement = 'all'/g" > $PGCONF
cat $PGCONF | sed "s/#listen_addresses = 'localhost'.*/listen_addresses = '*'/g" > $PGCONF
```
