### ISSUE TITLE
Persistent Data

### ISSUE THREAD

**Issue by Hamzantal** [docker-library/postgres#602]
Hi all, I apologise if this is the wrong place to ask, but I'm having trouble with my postgres docker container. I copied my `/var/lib/postgres` folder to a location with my docker-compose file, in an attempt to have persistent data for my postgres docker container. Unfortunately I have not been able to get the data to retain between restarts. Here is my docker compose file. Please let me know if I missed something trivial.

```yaml
version: '3.1'

services:
  db:
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: "muchsecure"
    volumes:
      - ./postgres:/var/lib/postgres
```
