### ISSUE TITLE
Can not login by specified user in environment

### ISSUE THREAD

**Issue by andrew-svirin** [docker-library/postgres#611]
I can not login by specified env:
My docker-compose.yml is
```
version: "3"

services:
  postgresql:
    container_name: 'postgresql'
    image: postgres:10-alpine
    environment:
      POSTGRES_DB: 'user'
      POSTGRES_USER: 'user_access'
      POSTGRES_PASSWORD: 'site_database'
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    networks:
      - app-tier
networks:
  app-tier:
    driver: bridge
```
On login i get this message:
```

postgresql    | 2019-09-30 15:27:50.988 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgresql    | 2019-09-30 15:27:50.988 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgresql    | 2019-09-30 15:27:50.992 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgresql    | 2019-09-30 15:27:51.032 UTC [18] LOG:  database system was interrupted; last known up at 2019-09-30 15:27:08 UTC
postgresql    | 2019-09-30 15:27:51.060 UTC [18] LOG:  database system was not properly shut down; automatic recovery in progress
postgresql    | 2019-09-30 15:27:51.063 UTC [18] LOG:  redo starts at 0/163FB20
postgresql    | 2019-09-30 15:27:51.063 UTC [18] LOG:  invalid record length at 0/163FB58: wanted 24, got 0
postgresql    | 2019-09-30 15:27:51.063 UTC [18] LOG:  redo done at 0/163FB20
postgresql    | 2019-09-30 15:27:51.076 UTC [1] LOG:  database system is ready to accept connections
postgresql    | 2019-09-30 15:28:10.592 UTC [27] FATAL:  password authentication failed for user "user"
postgresql    | 2019-09-30 15:28:10.592 UTC [27] DETAIL:  Role "user" does not exist.
postgresql    |         Connection matched pg_hba.conf line 95: "host all all all md5"
```

What do i need to change?
