### ISSUE TITLE
docker is not creating database

### ISSUE THREAD

**Issue by milanP96** [docker-library/postgres#625]
```
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: test
      POSTGRES_DATABSE: test
      POSTGRES_PASSWORD: test
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

```
On `psql -h 127.0.0.1 -U test`
get `psql: FATAL:  role "test" does not exist`
