### ISSUE TITLE
Minimum set of Linux capabilities?

### ISSUE THREAD

**Issue by hartwork** [docker-library/postgres#649]
Hi!

I'm trying to run the PostgreSQL docker image with the minimum set of Linux capabilities. This set seems to [work well so far](https://github.com/hartwork/jawanndenn/commit/593a85c914aff4d18af4bcc95293dc43e75354cb), superficially:

```
version: "3"

services:
  postgres:
    image: postgres:11.6
[..]
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_READ_SEARCH
      - FOWNER
      - SETGID
      - SETUID
```

Am I missing some capabilities that the service will not use in the first few minutes of operation but later in its lifetime? Does it need any where I am not likely to see errors in standard error/output?

Thanks and best, Sebastian

**Comment by tianon** [comment]
This is definitely very interesting work, but I'm afraid isn't something we really test for typically, not to mention most of it is going to be driven by PostgreSQL itself (so asking on a PostgreSQL mailing list would probably be your best bet, but even they probably won't have a good idea since it isn't something most folks worry about and isn't exactly trivial to measure and track).

**Comment by tommytran732** [comment]
> Hi!
> 
> I'm trying to run the PostgreSQL docker image with the minimum set of Linux capabilities. This set seems to [work well so far](https://github.com/hartwork/jawanndenn/commit/593a85c914aff4d18af4bcc95293dc43e75354cb), superficially:
> 
> ```
> version: "3"
> 
> services:
>   postgres:
>     image: postgres:11.6
> [..]
>     cap_drop:
>       - ALL
>     cap_add:
>       - CHOWN
>       - DAC_READ_SEARCH
>       - FOWNER
>       - SETGID
>       - SETUID
> ```
> 
> Am I missing some capabilities that the service will not use in the first few minutes of operation but later in its lifetime? Does it need any where I am not likely to see errors in standard error/output?
> 
> Thanks and best, Sebastian

Hi,
I wonder if you have ever figured it out. Why is FOWNER is needed? I am trying it without and it seems to work fine, but yeah I am not so sure if some operations in the future may need this :/

**Comment by hartwork** [comment]
@tommytran732 I added `FOWNER` back then because something was changing the owner of files on the fly, either in core PostgreSQL or on some layer above in the Docker image. The list was minimal back then, it may no longer be. The capabilities list in my initial post above is what I am still using with these two projects today:
- https://github.com/hartwork/wnpp.debian.net live at https://wnpp.debian.net/
- https://github.com/hartwork/jawanndenn live at https://jawanndenn.de/

That's all that I can say without further research.

**Comment by tommytran732** [comment]
Interesting, I am using the latest alpine image and I don't see it needing to change owner of files (at least there's no error visible in standard output anyways)

**Comment by tamalsaha** [comment]
@hartwork, thanks for this work. How did you determine these capabilities were required? We are trying to run postgres in Kubernetes and interested in finding out the minimally required capabilities.

**Comment by hartwork** [comment]
@tamalsaha if I remember correctly I started out with zero capabilities and reacted to the error output from PostgreSQL adding just the capabilities to address that every error until it was starting without errors.

**Comment by Jip-Hop** [comment]
Seems to work fine here with 0 capabilities.

```
docker info
Client: Docker Engine - Community
 Version:    25.0.1
```

```yaml
version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres:16.1
    volumes:
      - /mnt/postgres/data:/var/lib/postgresql/data
    # See https://github.com/docker-library/docs/blob/master/postgres/README.md#arbitrary---user-notes
    # Will still see the error:
    # "chmod: changing permissions of '/var/run/postgresql': Operation not permitted"
    # But this can be ignored:
    # https://github.com/docker-library/postgres/issues/853
    user: 2000:2000
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    read_only: true
    # https://github.com/docker-library/postgres/issues/154
    tmpfs:
      # For read-only filesystem, need to create a volume/tmpfs for PostgreSQL to run its much
      # needed configuration. The read-only flag does not make volumes and tmpfs read-only.
      - /tmp:noexec
      - /run:noexec
      - /run/postgresql:noexec
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    networks:
      postgres:
```

Database was already initialized. I then stopped the container, chowned the files inside `/mnt/postgres/data` to `2000:2000`.
