### ISSUE TITLE
port forward to host doesn't work

### ISSUE THREAD

**Issue by siben168** [docker-library/postgres#650]
I would like to use host port 5009 to access postgresql container, as so i used following compose file, the issue is, it seems the port forward definition doesn't work, i can't connent through 5009, however, i can connect DB in docker via port 5432. am i missing any config? 

docker-compose.yml
```
version: '3.7'

services:

  database:
    image: postgres
    container_name: postgres_1
    restart: on-failure:10
    volumes:
        - "pgvolume_1:/var/lib/postgresql/data"
    hostname: postgres_1
    networks:
        - pgnetwork_1
    environment:
      POSTGRES_PASSWORD: testpass
    ports:
        - "5009:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_1
    restart: on-failure:10
    volumes:
        - "C:/Users/eli2/AppData/Local/pgadmin:/var/lib/postgresql/data"
    ports:
      - "5051:80"
    hostname: pgadmin_1
    networks:
      - pgnetwork_1
    environment:
      PGADMIN_DEFAULT_EMAIL: eric.li@morningstar.com
      PGADMIN_DEFAULT_PASSWORD: testpass

networks:
    pgnetwork_1:

volumes:
    pgvolume_1:
```
