### ISSUE TITLE
Persisting data in Kubernetes

### ISSUE THREAD

**Issue by fschuindt** [docker-library/postgres#652]
I've been using this image for a while no with no problems, except that I don't think it's persisting information in the disks.

I'm using managed Kubernetes on Digital Ocean, everything runs great. Here's my setup:

**Postgres:**
```yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: gigs-psql-config-map
  namespace: gigsnet
  labels:
    owner: gigs-psql
data:
  PG_DATA: "/var/lib/postgresql/pgdata"
  POSTGRES_HOST: "gigs-psql-service"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "gigs_master"
  POSTGRES_DB: "gigs_master"
  POSTGRES_PASSWORD: "myPasswordHere"
---
apiVersion: v1
kind: Service
metadata:
  name: gigs-psql-service
  namespace: gigsnet
  labels:
    app: gigs-psql
spec:
  type: NodePort
  ports:
  - name: tcp
    protocol: TCP
    port: 5432
  selector:
    app: gigs-psql
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gigs-psql-deployment
  namespace: gigsnet
  labels:
    app: gigs-psql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gigs-psql
  template:
    metadata:
      name: gigs-psql-template
      labels:
        app: gigs-psql
    spec:
      containers:
        - image: postgres:12-alpine
          imagePullPolicy: Always
          name: gigs-psql-container
          livenessProbe:
            initialDelaySeconds: 180
            tcpSocket:
              port: 5432
          envFrom:
            - configMapRef:
                name: gigs-psql-config-map
          volumeMounts:
            - mountPath: /var/lib/postgresql/pgdata
              name: gigs-psql-pgdata-pvc
      volumes:
        - name: gigs-psql-pgdata-pvc
          persistentVolumeClaim:
            claimName: gigs-psql-pgdata-pvc
```
**PVC**:
```yml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gigs-psql-pgdata-pvc
  namespace: gigsnet
  labels:
    app: gigs-psql
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: do-block-storage
```

It works just fine until me or someone else deletes the Pod/Deployment. Deleting the Pod or Deployment will shut down the container but will leave the PVC there with the data written in it. The expected behavior is that the Postgres image will be able to recover the database state after creating the Pod, mounting the volume again, as happens with the MariaDB image, for instance.

But it's not happening. The container gets recreated, mounts the PVC but the database behaves like it was empty.

Any tip of what may be happening here or how to solve that?

Thank you!
