### ISSUE TITLE
Password from .env is cached

### ISSUE THREAD

**Issue by kingjerod** [docker-library/postgres#665]
I have a docker-compose file with this in it:
```
  postgres:
    image: postgres:9.6.12-alpine
    env_file: .env
    ports:
      - "54320:5432"
    volumes:
     - postgres_db_data:/var/lib/postgresql/data
```
In the .env file, I have the `POSTGRES_PASSWORD` along with everything else the container needs. At some point I had the password set to "B" and did a docker-compose up. I changed the password to "A" in the .env file and restarted the Postgres container, but it still has the password set to "B". 

I've tried restarting Docker, restarting Windows, tried updating the image version but it's still using "B". 

When I run `docker-compose config` I can see `POSTGRES_PASSWORD: A`. 
I've used `ash` to get into the container and run `echo $POSTGRES_PASSWORD` and it returns "A". 

I've tried changing the password to many other things in the .env file but it's stuck as "B".

Postgres Version: 9.6.3-alpine and 9.6.12-alpine
Win 10 Pro
Docker Desktop 2.1.04

Any commands I can do to fix this? Is there a cache for the container I can clear?
