### ISSUE TITLE
The data directory was initialized by PostgreSQL version 11, which is not compatible with this version 12.2.

### ISSUE THREAD

**Issue by alexisrolland** [docker-library/postgres#682]
Hello,

The following Dockerfile example works well in PostgreSQL 11 and the database is initialized with SQL files copied from the host `init` folder to the container `/docker-entrypoint-initdb.d`
```
FROM postgres:11.0-alpine
COPY ./init/ /docker-entrypoint-initdb.d/
```

But a similar Dockerfile for PostgreSQL 12 fails with the error below.
```
FROM postgres:alpine
COPY ./init/ /docker-entrypoint-initdb.d/
```

> The data directory was initialized by PostgreSQL version 11, which is not compatible with this version 12.2.

What would be the best way to reproduce the behavior from v11 to v12?
Thank you

**Comment by yosifkit** [comment]
Are you running them with the same volume? You cannot use the same database volume from 11 to 12.  You must do an upgrade to move between major versions. https://github.com/tianon/docker-postgres-upgrade is a good docker example of how to move from one to the next.

Here is upstream's documentation: https://www.postgresql.org/docs/current/upgrading.html

Duplicate of #37, #618.

**Comment by alexisrolland** [comment]
Thanks for hint about the volume! I think I was running them on different volume but I am not able to reproduce the issue today so maybe I just got confused and forgot to remove the v11 volume before running v12.

Note I let Docker create the volume automatically with Docker Compose like this. Would there be a better way to do that?

```
version: "3.1"
services:
    db:
        container_name: mobydq-db
        restart: always
        image: mobydq-db
        build:
            context: ./db
        volumes:
            - db:/var/lib/postgresql/data
        env_file:
            - ./.env
        networks:
            - network

networks:
    network:

volumes:
    db:
```
