### ISSUE TITLE
Postgres data folder empty on kubernetes

### ISSUE THREAD

**Issue by MK-2001** [docker-library/postgres#696]
# Describe the situation
We are using postgres 11.7. We mount the data volume on /var/lib/postgresql via an cider pvc.
When we use the path /var/lib/postgresql/data the mount will be done with the permissions root:postgres. In this case postgres is not able to takeover the ownership for the folder .../data and aborts the startup with the message "Opertation not permitted".

When we mount the dir /var/lib/postgresql we can see the folders /var/lib/postgesql/data and during postgres is running there are all needed files. But after we stopped the container the folder .../data is empty.

# What is expected 
After shutdown the container there should be all data still available within the folder /var/lib/postgresql/data.

# Alternative solutions:
The startup script may be not need the User-Ownership of the folder /var/lib/postgresql/data then it does not interrupt the startup.

# Questions:
How to handle postgres with a docker image on kubernetes?
Is the .../data directory an hardlink directy? 
Why there are no failes anymore in the directory after shutdown?

# Similiar issues:
#103 / #560 
- But in kubernetes it is not possible to mount an volume not as root user. Just the group is changeable.
- it seem to be an locking issue between postgres and k8s

**Comment by MK-2001** [comment]
Currently found an Workaround:
https://github.com/docker-library/postgres/issues/116#issuecomment-490241287

Is is only possible to mount the directory `/var/lib/postgresql/data` directly and use PGDATA env.-variable to use a different subdirectory like `/var/lib/postgresql/data/pgdata`. 

It was not possible to move the directory outsite of /var/lib/postgresql/data like /usr/postgresql/data or other locations.

**Comment by yosifkit** [comment]
> When we mount the dir /var/lib/postgresql we can see the folders /var/lib/postgesql/data and during postgres is running there are all needed files. But after we stopped the container the folder .../data is empty.

The answer is here: https://github.com/docker-library/postgres/issues/103#issuecomment-167631548 (quote below):

>Indeed.  Because "/var/lib/postgresql/data" is marked as a VOLUME in the
Dockerfile, Docker will always create a new volume there unless it's
explicitly mounted over top of, even if "/var/lib/postgresql" is a volume
above it.

---

>How to handle postgres with a docker image on kubernetes?

While the `postgres` image was improved to support running as an "arbitrary user" (#253), it doesn't really like to.

> The main caveat to note is that postgres doesn't care what UID it runs as (as long as the owner of `/var/lib/postgresql/data` matches), but initdb does care (and needs the user to exist in /etc/passwd):

So, the database folder **must** be owned by the user running postgres.  The easiest way to do that is to define `PGDATA` to a subdirectory of a directory writable by the running user (so, a subdirectory of your kubernetes-defined volume). This way the `postgres` user can create and chmod the directory for itself (since it can't change permissions of the "cider pvc").

```yaml
    volumeMounts:
    - name: postgres-data
      mountPath: /var/lib/postgresql/data
    env:
    - name: PGDATA
      value: /var/lib/postgresql/data/pgdata
```

> It was not possible to move the directory outsite of /var/lib/postgresql/data like /usr/postgresql/data or other locations.

Were those defined the same, i.e. `PGDATA` was a subdirectory of the volume?

---

>Is the .../data directory an hardlink directy?
>Why there are no failes anymore in the directory after shutdown?

It is a `VOLUME`. See quote above (https://github.com/docker-library/postgres/issues/103#issuecomment-167631548)

**Comment by walec51** [comment]
this is such a crazy issue I thought it was a problem on Kubernetes level:

https://github.com/digitalocean/csi-digitalocean/issues/289

postgreses Dockerfile enforced you to mount something to `/var/lib/postgresql/data` however i you try to mount a persistent volume claim it will fail suggesting you to mount it to `/var/lib/postgresql/`

but if you mount it to `/var/lib/postgresql/` you end up with a persistent volume in which the `data` directory will be wiped by your docker pod / container on each restart

lost two days on tinkering due to this

my workaround was to change the PGDATA directory to a totally different one:

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-reservation-db
  namespace: staging
spec:
  serviceName: postgres-reservation-db
  replicas: 1
  selector:
    matchLabels:
      app: postgres-reservation-db
  template:
    metadata:
      labels:
        app: postgres-reservation-db
    spec:
      containers:
        - name: postgres
          image: postgres:12.2
          env:
          - name: PGDATA
            value: /work/data
          - name: POSTGRES_PASSWORD
            value: someTestPassword
          ports:
          - containerPort: 5432
          resources:
            requests:
              cpu: "200m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          volumeMounts:
          - name: data
            mountPath: /work
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Gi
```
