### ISSUE TITLE
Support changing the listening port via $POSTGRES_PORT

### ISSUE THREAD

**Issue by cansjt** [docker-library/postgres#702]
I am aware of issues #302 and #196. I do believe, though, the issue still hasn't been properly addressed.

Indeed in those issues, the solutions provided all assumes you are in control of the command line that starts the container (with docker) or use docker-compose. But there are plenty of use cases where these assumptions do not hold. Especially in a cloud context. PaaS and CI/CD systems, to name a few, do not necessarily let you provide extra arguments to the container's startup command line. Leaving us with environment variables as the only mean to configure the container (if you don't want to build a docker image of your own).

It would be extremely helpful if that feature was implemented here, instead of having to implement it on your own when needed.

So, please, do reconsider implementing this (#196 contains a solution, though I have not tested it). Thanks.

**Comment by tianon** [comment]
All the CI/CD systems I'm aware of that didn't previously allow customizing the container command have since added support for doing so (since customizing the container command is every bit as important for customizing a container as environment variables are).  Do you have any more specific examples of systems which still do not support modifying command?

**Comment by cansjt** [comment]
@tianon Sorry for the lag. We use [CircleCI](https://circleci.com/docs/2.0/configuration-reference/#section=configuration). Their CI system is container based, you can do some level or Docker in Docker, but mostly to build docker images, not to run docker containers as services. They do offer VMs but their VM images are clearly not their priority and quite outdated. Which leads you to lengthy updates within the CI build itself, which is a waste of time, on top of the VM start-up time which is not great.

**Comment by yosifkit** [comment]
`command` is in the docker section of the documentation that you link to:

```yaml
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty # primary container
        environment:
          ENV: CI

      - image: mongo:2.6.8
        command: [--smallfiles]

      - image: postgres:9.4.1
        environment:
          POSTGRES_USER: root

      - image: redis@sha256:54057dd7e125ca41afe526a877e8bd35ec2cdd33b9217e022ed37bdcf7d09673
```

So you should be able to add command to postgres just like they do to `mongo`.
