### ISSUE TITLE
Permissions error with chmod

### ISSUE THREAD

**Issue by Parkbro** [docker-library/postgres#706]
Hello,

I am having issues getting my docker containers up and running without restarting. The first two containers are running without any issues but the postgres one (tried on 10.11 and 10.12) is thowing the error:

    chmod: changing permissions of '/var/lib/postgresql/data': Operation not permitted

I am running from an elevated powershell window if that matters. Would it be as simple as setting the user to a different value than the default? I am afraid that I can't get into the container itself to see what is going wrong beyond the message above as that is all that:

    docker-compose logs db

is supplying to me. I recognise that it may be something that I have done but in the off chance that it is not wanted to make you aware. Thank you.

```yml
version: '3'
services:
  nginx:
    restart: always
    image: nginx:latest
    container_name: ng01
    networks:
      - default
    ports:
      - "80:80"
    volumes:
      - .:/src
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    restart: on-failure:5
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dg01
    env_file:
      - .env
    command: bash -c "python pmv3/manage.py runserver 0.0.0.0:8000" # Do this after makemigrations && python pmv3/manage.py migrate && cd pmv3 &&  gunicorn --config=gunicorn_config.py pmv3.wsgi:application"
    depends_on:
      - db
    volumes:
      - .:/src
    expose:
      - "8000"
    networks:
      - default
  db:
    image: postgres:10.12
    container_name: pg01
    restart: always
    environment:
      POSTGRES_DB: a
      POSTGRES_USER: b
      POSTGRES_PASSWORD: c
    ports:
      - "5432:5432"
    volumes:
    - ./sql_backups:/home
    - pg_data:/var/lib/postgresql/data


volumes:
  pg_data:
```

Docker version 17.10.0-ee-preview-3, build 1649af8
docker-compose version 1.25.4, build 8d51620a
Windows Server 2019 Datacenter

The suggestion in a suggested thread to try:
    
    pg_data:/var/lib/postgresql/data:z 

did not work either

Trying to add the environmental variable 

    PG_DATA: /var/lib/postgresql/data/pgdata
doesn't work nor does adding
    user: root

I do recall in Docker desktop there is an option to give permission to the c:drive but I don't know if that is required with this version of docker.

Cheers

Edit: Ended up just switching from a windows server to an ubuntu one and it worked instantly.
