### ISSUE TITLE
[33] FATAL:  password authentication failed for user "postgres" after image update

### ISSUE THREAD

**Issue by junpet** [docker-library/postgres#723]
I'm using almost a year my postgres container. I've started with version 11 back then, successfully upgraded to version 12 in the past. Currently using the latest version.

I check if there's new image for the tag `12`. There was some updates in the last month, but I had no time to pull the image, because I've plenty other containers using the database, so I've to stop them first.

So, I thought I pull the latest image. 
1. Stopped all of the containers using the database. `docker-compose down`
2. Stopped postgres. `docker-compose down`
3. Pulled the image. `docker-compose pull`
4. Started postgres container.  `docker-compose up`

When I started the container I got 
```
[33] FATAL:  password authentication failed for user "postgres"
[33] DETAIL:  Password does not match for user "postgres".
Connection matched pg_hba.conf line 95: "host all all all md5"
[34] FATAL:  password authentication failed for user "postgres"
[34] DETAIL:  Password does not match for user "postgres".
Connection matched pg_hba.conf line 95: "host all all all md5"
.
.
.
```
And so on. I've panicked, because there was no postgres update, only the docker image was updated. I searched on the net, but could not find anything. However I can connect to the postgres database with `docker exec -it postgres psql -U postgres`, and I can connect with pgadmin as well, but still the container spamming authentication failure, which is not healthy I guess. I use the same `docker-compose.yml` and `.env` like before pulling the newest image.

My `docker-compose.yml` for reference. 
```yml
version: "3.7"

services:
  db:
    image: postgres:12
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-network

volumes:
  postgres-data:
    driver: local-persist
    driver_opts:
      mountpoint: "${DOCKER_VOLUMES}/postgres"

networks:
  postgres-network:
    external: true
```

---
TL;RD:
I can connect with the password using pgadmin, but the container spamming authentication failure after starting. Can you help me?
