### ISSUE TITLE
How to make postgres available locally only?

### ISSUE THREAD

**Issue by cuzox** [docker-library/postgres#743]
I have the following docker-compose:
```
  db:
    ports:
      - "5432:5432"
    image: postgres:11
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
```

This is making the postgres db accessible from the internet (`ingress`?), but I only want it to be accessible to my other docker swarm services and when connected to the server through a VPN.
2 things:
1. I understand I have to modify the `pg_hba.conf` file, but I can't find an official source that touches on how to do this
2. The things that need to be in that file are `host all all [server_ip] md5` and `host all all 0.0.0.0 reject`? Would that allow the other docker services to access it?

**Comment by yosifkit** [comment]
If it is just other docker services on the same `docker network`, then get rid of the `ports`.  The `ports` config is what makes it available on the host at `5432` to anyone that can hit that port.

**Comment by cuzox** [comment]
Thank you for the prompt reply! I have it on a Linux VPS inside of which I'm running Open VPN, and I want it to also be accessible from my local machine while connected 🤔

**Comment by tianon** [comment]
If you're not using a swarm service and this is just run via `docker-compose`, you could just change `"5432:5432"` in your `docker-compose.yml` to be `"127.0.0.1:5432:5432"` or `"192.168.0.NNN:5432:5432"` (where `192.168.0.NNN` is the IP address of the VM's VPN interface).

**Comment by cuzox** [comment]
I failed to mention that it's indeed deployed with docker swarm

**Comment by cuzox** [comment]
I have 2 `docker-compose`, one for production, another with development overrides. In the dev one I added:
```
  db:
    ports:
      - "127.0.0.1:5432:5432"
```
and it works well locally, but when I add the following to my prod file:
```
  db:
    ports:
      - "192.168.0.XXX:5432:5432"
```
it stops working locally...
But either way @tianon you're saying it won't work because I'm deploying with swarm?

**Comment by tianon** [comment]
That would be thanks to https://github.com/moby/moby/issues/26696 -- when you specify an IP address in Swarm, it is ignored and binds to `0.0.0.0`, which is why your second bind wouldn't work and why `127.0.0.1:5432:5432` is still available to the internet.

If you're deploying with `docker-compose`, you can list both IPs and that should work:

```yaml
  db:
    ports:
      - "127.0.0.1:5432:5432"
      - "192.168.0.XXX:5432:5432"
```
