### ISSUE TITLE
Can I control host address in pg_setup_hba_conf function?

### ISSUE THREAD

**Issue by worldofsites** [docker-library/postgres#752]
I need to have more control for [pg_setup_hba_conf](https://github.com/docker-library/postgres/blob/88173efa530f1a174a7ea311c5b6ee5e383f68bd/12/docker-entrypoint.sh#L218) function which call in [docker-entrypoint.sh](https://github.com/docker-library/postgres/blob/88173efa530f1a174a7ea311c5b6ee5e383f68bd/12/docker-entrypoint.sh)
In https://hub.docker.com/_/postgres?tab=description described:
```echo "host all all all $POSTGRES_HOST_AUTH_METHOD" >> pg_hba.conf```
I want to avoid adding that line or use it in something like:
```echo "host all all $POSTGRES_HOST_AUTH_ADDRESS $POSTGRES_HOST_AUTH_METHOD" >> pg_hba.conf```

And in that case ```POSTGRES_HOST_AUTH_ADDRESS```  by default would be ```all```.

My case:
I have docker-compose.yaml
```
version: "3.8"

volumes:
  test_postgres_database:

services:
  postgres:
    image: "postgres:12"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 1G
    container_name: "test-postgres"
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_EXPOSE_PORT}:5432"
    volumes:
      - test_postgres_database:/var/lib/postgresql/data
      - ./init/postgres/init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
      - ./init/postgres/init.sh:/docker-entrypoint-initdb.d/init.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      test-network:
        aliases:
          - postgres
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: "test-pgadmin"
    restart: always
    environment: 
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
    ports: 
      - "16543:80"
    depends_on:
      - postgres
    networks:
      test-network:
        aliases:
          - pgadmin

#...
#and many other services which can connect to postgres in test-network subnet
#...

networks:
  test-network:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.19.0.0/16
```
Used not in swarm.
Used with ```--compatibility``` param when build and up.

and init.sh:
```
echo "host all  all  172.19.0.0/16  md5" >> /var/lib/postgresql/data/pg_hba.conf
```

I want to having access to postgres only within that subnet and nowhere else.
But in current implementation I always see ```host all all all trust``` in ```/var/lib/postgresql/data/pg_hba.conf``` before my custom rule ```host all  all  172.19.0.0/16  md5```

Maybe I'm doing something wrong?
I would like to have more control of adding the default line ```host all all all trust``` or possibility to change not only auth method parameter.

Thanks!
