### ISSUE TITLE
Container not working when commands are in dockerfile

### ISSUE THREAD

**Issue by kpeter477** [docker-library/postgres#760]
I have this dockerfile:
```
FROM postgres:12

COPY folders/db_backup_script.sh /usr/local/bin/db_backup_script.sh
# RUN chmod +x /usr/local/bin/db_backup_script.sh

# EXPOSE 5432

# RUN apt-get update && apt-get install -y cron p7zip-full

# # Run the cron 30 every minute
# RUN echo '*/30  *  *  *  *    /usr/local/bin/db_backup_script.sh' > /etc/cron.d/backup-job
# RUN crontab /etc/cron.d/backup-job

# CMD ["cron", "-f"]
```
And this docker-compose:
```
    postgres:
    build:
      context: .
      dockerfile: postgres.dockerfile
    mem_limit: 2048M
    mem_reservation: 300M
    environment:
      POSTGRES_PASSWORD: abcd
    restart: unless-stopped
    volumes:
      - /data/erp/db:/var/lib/postgresql
      - /data/erp/db_backup:/db_backup
    networks:
      - app_net
    ports:
      - 5432:5432
```
This is working fine. When I uncomment commands in dockerfile, and build&run it again with docker-compose, everythink is OK and seem to be fine, but database is unavailable, shuts the connection immidiately. How can I solve this? Cron is working with echo, I could not test it with backup. It fails even if there is only the install line. Any idea?
