### ISSUE TITLE
Container reinit database on rebuild

### ISSUE THREAD

**Issue by kpeter477** [docker-library/postgres#761]
I have the following docker-compose script which resets the whole database server to initial state when I run docker-compose build:
```
postgres:
    image: postgres:12
    mem_limit: 2048M
    mem_reservation: 300M
    environment:
      POSTGRES_PASSWORD: abcd
    restart: unless-stopped
    volumes:
      - /data/erp/db:/var/lib/postgresql
    networks:
      - app_net
    ports:
      - 5432:5432
```
How can I avoid this? Nothing is removing content on the host.
