### ISSUE TITLE
docker_entrypoint_initdb.d script fails to find gen_random_uuid()

### ISSUE THREAD

**Issue by rpatrick00** [docker-library/postgres#776]
I am using the postgres:11.9 image in docker-compose.  My docker-compose entry looks like this:

```
  postgresql:
    image: postgres:11.9
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=p0stgr3s
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - "./postgres/data:/var/lib/postgresql/data"
      - "./postgres/initdb.d:/docker-entrypoint-initdb.d"

```

My initdb.d directory contains a single SQL file with the following contents:

```
CREATE USER test_dba WITH PASSWORD 'P@ssw0rd';
GRANT test_dba TO postgres;
CREATE DATABASE test_db WITH OWNER test_dba ENCODING UTF8;
GRANT ALL PRIVILEGES ON DATABASE test_db TO test_dba;
CREATE USER test_user WITH PASSWORD 'P@ssw0rd';
GRANT CONNECT ON DATABASE test_db TO test_user;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

\c test_db

CREATE TABLE test_table (
    id UUID DEFAULT gen_random_uuid(),
    name VARCHAR NOT NULL,
    PRIMARY KEY (id)
);
```

When I bring up the container, I see the following output which seems to indicate the the pgcrypto extension was created but the gen_random_uuid() function is still not being found:

```
postgresql_1                  | 2020-10-22 00:13:54.087 UTC [48] LOG:  database system is ready to accept connections
postgresql_1                  |  done
postgresql_1                  | server started
postgresql_1                  |
postgresql_1                  | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/01_init.sql
postgresql_1                  | CREATE ROLE
postgresql_1                  | GRANT ROLE
postgresql_1                  | CREATE DATABASE
postgresql_1                  | GRANT
postgresql_1                  | CREATE ROLE
postgresql_1                  | GRANT
postgresql_1                  | CREATE EXTENSION
postgresql_1                  | You are now connected to database "test_db" as user "postgres".
postgresql_1                  | 2020-10-22 00:13:56.817 UTC [65] ERROR:  function gen_random_uuid() does not exist
postgresql_1                  | 2020-10-22 00:13:56.817 UTC [65] HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
postgresql_1                  | 2020-10-22 00:13:56.817 UTC [65] STATEMENT:  CREATE TABLE test_table (
postgresql_1                  |             id UUID DEFAULT gen_random_uuid(),
postgresql_1                  |             name VARCHAR NOT NULL,
postgresql_1                  |             PRIMARY KEY (id)
postgresql_1                  |         );
postgresql_1                  | psql:/docker-entrypoint-initdb.d/01_init.sql:15: ERROR:  function gen_random_uuid() does not exist
postgresql_1                  | HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
cap-dev-compose_postgresql_1 exited with code 3
```

All of this works fine on my AWS RDS instance (version 11.6) so I don't understand why it is failing with the containerized 11.9 version.
