### ISSUE TITLE
Issue with the usage of the image

### ISSUE THREAD

**Issue by Ddzhenyik** [docker-library/postgres#783]
When I try to use the image I receive odd errors... It happens only when I try to add "volume" (without volumes everything works fine). 

The `docker-compose.yml` file content: 

```
version: '3'
services:

#  strapi:
#    image: strapi/strapi
#    environment:
#      DATABASE_CLIENT: postgres
#      DATABASE_NAME: strapi
#      DATABASE_HOST: postgres
#      DATABASE_PORT: 5432
#      DATABASE_USERNAME: strapi
#      DATABASE_PASSWORD: strapi
#    links:
#      - postgres:postgres
#    volumes:
#      - ./app:/srv/app
#    ports:
#      - '1337:1337'

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

```
The errors I received: 

> Creating strapi-proj_postgres_1 ... done
Attaching to strapi-proj_postgres_1
postgres_1  | The files belonging to this database system will be owned by user "postgres".
postgres_1  | This user must also own the server process.
postgres_1  | 
postgres_1  | The database cluster will be initialized with locale "en_US.utf8".
postgres_1  | The default database encoding has accordingly been set to "UTF8".
postgres_1  | The default text search configuration will be set to "english".
postgres_1  | 
postgres_1  | Data page checksums are disabled.
postgres_1  | 
postgres_1  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
postgres_1  | creating subdirectories ... ok
postgres_1  | selecting dynamic shared memory implementation ... posix
postgres_1  | selecting default max_connections ... 100
postgres_1  | selecting default shared_buffers ... 128MB
postgres_1  | selecting default time zone ... Etc/UTC
postgres_1  | creating configuration files ... ok
postgres_1  | running bootstrap script ... 2020-11-08 20:52:38.581 UTC [38] FATAL:  unexpected data beyond EOF in block 0 of relation base/1/1249
postgres_1  | 2020-11-08 20:52:38.581 UTC [38] HINT:  This has been seen to occur with buggy kernels; consider updating your system.
postgres_1  | 2020-11-08 20:52:38.581 UTC [38] PANIC:  cannot abort transaction 1, it was already committed
postgres_1  | Aborted
postgres_1  | child process exited with exit code 134
postgres_1  | initdb: removing contents of data directory "/var/lib/postgresql/data"
strapi-proj_postgres_1 exited with code 1

Few more things to mention: 
1. OS: MacOS Catalina 10.15.7
2. When I try to use volume `- /tmp/data:/var/lib/postgresql/data` everything works fine (but it's not an option since I need to persist the data)
3. "./data" folder has next permissions: `drwxr-xr-x`

Maybe someone faced the same issue?
