### ISSUE TITLE
Permission Denied and Directory "/var/lib/postgresql/data/pg" exists but is not empty with NFS PVC

### ISSUE THREAD

**Issue by danroot** [docker-library/postgres#792]
I am attempting to set up a postgres container with data files stored in an NFS share.  When I attempt this the pod fails with status of CrashLoopBackOff.  Using kubectl logs <name>, I think it first fails with:

```
fixing permissions on existing directory /var/lib/postgresql/data ... ok
initdb: error: could not create directory "/var/lib/postgresql/data/pg_wal/archive_status": Permission denied
initdb: removing contents of data directory "/var/lib/postgresql/data"
initdb: warning: could not open directory "/var/lib/postgresql/data/global": Permission denied
initdb: warning: could not open directory "/var/lib/postgresql/data/pg_wal": Permission denied
initdb: error: failed to remove contents of data directory
creating subdirectories ...
```
Then subsequent initialization attempts fail with:
```
initdb: error: directory "/var/lib/postgresql/data/pg" exists but is not empty
If you want to create a new database system, either remove or empty
the directory "/var/lib/postgresql/data/pg" or run initdb
with an argument other than "/var/lib/postgresql/data/pg".
```

As best I can tell, what is happening is:

1) the container starts and sees the data folder empty
2) it creates the folders pg_wal and global
3) it tries to access them and gets permission denied
4) it attempts chown -R 999:999 $PGDATA
5) it continues failing init
6) subsequent init attempts fail because pg_wal and global are in the folder.

I see from other issue reports that there have been some changes around this as it previously overwrote data in $PGDATA. I am hoping someone can point me in the right direction on this.  In the end I don't need HA or great performance.  I just want a small single replica postgres pod where the data is persisted to our storage array (which can expose NFS and other flavors) and not local storage on the kubernetes host.

A couple specific questions:
1) How can I best modify the yaml below so that this scenario works with no errors?
2) Why must $PGDATA be empty or be overwritten?  My expected behavior is that IF database files exist in the folder, it mounts them and uses them.  Is there a flag or something to cause this behavior?

To repro:
Ensure you have a NFS share exposed and update the yaml below with the correct paths.  Then run kubectl apply -f nameoffile.yaml
Run kubectl get pods, observe Error, then CrashLoopBackOff
Run kubectl log pod <name> to observe behavior described above

```
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-database-pv  
spec:
  capacity:
    storage: 5Gi 
  accessModes:
  - ReadWriteMany
  nfs: 
    path: /nfsserver/somepath/database
    server: platform.mycompany.com
---              
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: harbor-database-pvc
spec:
   accessModes:
     - ReadWriteMany
   storageClassName: ""
   resources:
     requests:
       storage: "1Gi"
   volumeName: "harbor-database-pv"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbor-postgres
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: harbor-postgres
  template:
    metadata:
      labels:
        app: harbor-postgres
    spec:    
      containers:
      - name: postgres
        image: postgres:13
        imagePullPolicy: "Always"
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: pgbench
        - name: PGUSER
          value: pgbench
        - name: POSTGRES_PASSWORD
          value: postgres@123
        - name: PGBENCH_PASSWORD
          value: superpostgres
        - name: PGDATA
          value: /var/lib/postgresql/data/pg
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgredb
      volumes:
      - name: postgredb
        persistentVolumeClaim:
          claimName: harbor-database-pvc
```
