### ISSUE TITLE
Any ways to separate data and settings volume

### ISSUE THREAD

**Issue by vlapenkov** [docker-library/postgres#793]
Hello,
I have such section in  docker-compose,
```
postgres:  
    image: postgres 
    container_name: postgres01
    environment:  
      POSTGRES_PASSWORD: BigPassw0rd
      POSTGRES_HOST_AUTH_METHOD: trust
    ports: 
      - 5432:5432
    volumes:
      - datapostgre:/var/lib/postgresql/data 
``` 
What i need is to store  data and postgresql.conf+pg_hba.conf on distinct volumes.
Thanks in advance!
