### ISSUE TITLE
Any postgresql 13.x ARMHL image crashes with segfault 

### ISSUE THREAD

**Issue by agilob** [docker-library/postgres#836]
```
pi@rpi1:~ $ docker-compose -f postgres-compose.yaml up
Starting postgresql ... done
Attaching to postgresql
postgresql    | The files belonging to this database system will be owned by user "postgres".
postgresql    | This user must also own the server process.
postgresql    |
postgresql    | The database cluster will be initialized with locale "en_US.utf8".
postgresql    | The default database encoding has accordingly been set to "UTF8".
postgresql    | The default text search configuration will be set to "english".
postgresql    |
postgresql    | Data page checksums are disabled.
postgresql    |
postgresql    | fixing permissions on existing directory /var/lib/postgresql/data ... ok
postgresql    | creating subdirectories ... ok
postgresql    | selecting dynamic shared memory implementation ... posix
postgresql    | selecting default max_connections ... 100
postgresql    | selecting default shared_buffers ... 128MB
postgresql    | selecting default time zone ... GMT
postgresql    | creating configuration files ... ok
postgresql    | running bootstrap script ... ok
postgresql    | performing post-bootstrap initialization ... sh: locale: not found
postgresql    | 1970-05-17 17:01:28.011 GMT [31] WARNING:  no usable system locales were found
postgresql    | ok
postgresql    | syncing data to disk ... ok
postgresql    |
postgresql    |
postgresql    | Success. You can now start the database server using:
postgresql    |
postgresql    |     pg_ctl -D /var/lib/postgresql/data -l logfile start
postgresql    |
postgresql    | initdb: warning: enabling "trust" authentication for local connections
postgresql    | You can change this by editing pg_hba.conf or using the option -A, or
postgresql    | --auth-local and --auth-host, the next time you run initdb.
postgresql    | waiting for server to start....1970-05-19 23:38:16.011 GMT [36] LOG:  starting PostgreSQL 13.2 on arm-unknown-linux-musleabihf, compiled by gcc (Alpine 10.2.1_pre1) 10.2.1 20201203, 32-bit
postgresql    | 1970-05-19 23:38:16.011 GMT [36] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgresql    | ...........1970-05-19 23:38:16.011 GMT [36] LOG:  startup process (PID 37) was terminated by signal 11: Segmentation fault
postgresql    | 1970-05-19 23:38:16.011 GMT [36] LOG:  aborting startup due to startup process failure
postgresql    | 1970-05-19 23:38:16.011 GMT [36] LOG:  database system is shut down
postgresql    |  stopped waiting
postgresql    | pg_ctl: could not start server
postgresql    | Examine the log output.
postgresql exited with code 1
```

Using this docker-compose:

```
version: "3.3"

services:
  postgresql:
    image: postgres:13.2-alpine
    container_name: postgresql
    hostname: postgres
    volumes:
      - $HOME/dockers/pg/data:/var/lib/postgresql/data:rw
      - $PWD/pg:/etc/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - MAX_CONNECTIONS=10
      - MAX_WAL_SENDERS=5
    ports:
      - 5432:5432
```

i've tried ubuntu and alpine images, but they all crash. 12.4 works fine.

`Linux rpi1 5.10.17+ #1403 Mon Feb 22 11:26:13 GMT 2021 armv6l GNU/Linux`
