### ISSUE TITLE
setting up for matrix server

### ISSUE THREAD

**Issue by leon1995** [docker-library/postgres#840]
Hi,

I am trying to setup a postgres db using docker for a matrix server.
The matrix server requires the db to have `LC_CTYPE=C` and `LC_COLLATE=C` to be set. However, when I set these in my docker-compose file, then the default encoding is `SQL_ASCII`, which is not compatible, because utf8 is required. I have not found an option, where I can set the encoding for the database, when both env vars are set. `LC_ALL=en_US.UTF-8` seems to override both of them.

I hope you can help me :)

**Comment by arctichomelab** [comment]
I also had this issue. After much digging, I found [this site which specified the -E flag (step 5)](https://www.shubhamdipt.com/blog/how-to-change-postgresql-database-encoding-to-utf8/), [and I found there was an environment variable to initdb - so I poked](https://github.com/docker-library/docs/tree/master/postgres#postgres_initdb_args) I also followed the [Matrix documentation here](https://github.com/matrix-org/synapse/blob/develop/docs/postgres.md).

I'm not sure if this is correct, or even proper. It seems to have worked when I migrated from the sqlite db.

Here is my compose:

```
  matrix-synapse-db:
    image: postgres:13-alpine
    container_name: matrix-synapse-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: synapse
      POSTGRES_DB: synapse
      POSTGRES_PASSWORD: supercomplexpassword
      POSTGRES_INITDB_ARGS: '-E "UTF8"'
      LC_COLLATE: 'C'
      LC_CTYPE: 'C'
```
