### ISSUE TITLE
How to import a backup when starting new container using docker-compose ?

### ISSUE THREAD

**Issue by XDavidT** [docker-library/postgres#847]
I have service that depend in objects that need to already be in my DB. (I'm building container to existing app)
How to load the backup into a new docker container ?
Here is my docker-compose:
```
version: "3.9"
services:

 web:
  image: xdavidt/meta-data-service
  restart: always
  depends_on:
   - db
  links:
   - "db:database"

 db:
  image: postgres
  restart: always
  ports:
   - "5432:5432"
  environment:
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: mysecretpassword
   POSTGRES_DB: location_counter
  volumes:
   - ./data:/data
  command: ./data/run.sh
```

and here is my run.sh:

```
#!/bin/bash

pg_restore -U postgres -d location_counter ./data/template.sql
```

So, based on this information, there is error 'permission denied' and if change the command to:
"chmod +x ./data/run.sh"
output say no db named "location counter"
