### ISSUE TITLE
Syntax error while using docker-entrypoint-initdb.d

### ISSUE THREAD

**Issue by andreafspeziale** [docker-library/postgres#856]
Hello and thank you for your hard work.
I'm struggling trying to use the `docker-entrypoint-initdb` feature.

I've the following syntax error but unfortunately I'm not able to fix it.

```
/usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/data.sql
psql-documents | CREATE SCHEMA
psql-documents | 2021-06-08 15:55:22.718 UTC [82] ERROR:  syntax error at or near "" at character 1
psql-documents | 2021-06-08 15:55:22.718 UTC [82] STATEMENT:
psql-documents | 	CREATE TYPE document_validation_step AS ENUM (
psql-documents | 	    'PENDING',
psql-documents | 	    'NO_VALIDATION_REQUIRED',
psql-documents | 	    'VALID',
psql-documents | 	    'INVALID'
psql-documents | 	);
psql-documents | psql:/docker-entrypoint-initdb.d/data.sql:8: ERROR:  syntax error at or near ""
psql-documents | LINE 1:
psql-documents |         ^
psql-documents exited with code 3
```

My testing `docker-compose`

```
version: "3.7"

services:
  db:
    image: postgres:latest
    container_name: psql-documents
    ports:
      - 5432:5432
    environment:
        POSTGRES_DB: documents-db
        POSTGRES_USER: db-user
        POSTGRES_PASSWORD: secretpassword
    volumes:
        - psql-documents:/var/lib/postgresql/data
        - ./migration/data.sql:/docker-entrypoint-initdb.d/data.sql
volumes:
    psql-documents:   
```

My `data.sql`

```
CREATE SCHEMA document;
​
CREATE TYPE document_validation_step AS ENUM (
    'PENDING',
    'NO_VALIDATION_REQUIRED',
    'VALID',
    'INVALID'
);
​
CREATE TYPE document_side AS ENUM (
    'FRONT',
    'BACK',
    'FULL'
);
​
CREATE TYPE document_type AS ENUM (
    'OTHER',
    'ID_CARD',
    'PASSPORT',
    'DRIVING_LICENSE',
    'FISCAL_CODE',
    'HEALTH_INSURANCE_CARD',
    'PAYSLIP',
    'SIGNED_CONTRACT',
    'LOAN_REQUEST',
    'SECCI'
);
​
CREATE TABLE document.uploads (
    id bigint NOT NULL,
    folder character varying(256) NOT NULL,
    type document_type NOT NULL,
    side document_side NOT NULL,
    filename character varying(256) NOT NULL,
    reference character varying(1024),
    ocr_documents jsonb,
    validation document_validation_step,
    exception_code character varying(10),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT pk_document_uploads_id PRIMARY KEY (id)
);
​
CREATE TABLE document.template_mappings (
    id bigint NOT NULL,
    template_id bigint NOT NULL,
    mapping jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT pk_document_template_mappings_id PRIMARY KEY (id)
);
​
​CREATE TABLE document.templates (
    id bigint NOT NULL,
    document_code character varying(255) NOT NULL,
    filename character varying(255) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    document_type character varying(128),
    CONSTRAINT pk_document_templates_id PRIMARY KEY (id),
    CONSTRAINT uq_document_templates_document_code UNIQUE (document_code)
);
```

What am I missing?
