### ISSUE TITLE
Using `POSTGRES_PASSWORD_FILE` instead of `POSTGRES_PASSWORD` env?

### ISSUE THREAD

**Issue by oerp-odoo** [docker-library/postgres#882]
I see https://github.com/docker-library/postgres/blob/b4b726dbf1885e8e1543526ad9d250fdb2689cbb/12/alpine/docker-entrypoint.sh#L9

that it mentions that you can either use environment variables or pass files named as `VARIABLE_NAME_FILE`. Though, I don't understand if it ever tries to read such supplied files and where it does expect those files to be?

I have this compose file:

```yaml
version: "3"
services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=myuser
      - POSTGRES_PORT=5432
    volumes:
      - db-data:/var/lib/postgresql/data
      - type: bind
        source: ./secrets/POSTGRES_PASSWORD_FILE
        target: /POSTGRES_PASSWORD_FILE
volumes:
  db-data:
    driver: local
```

So I see file being put inside container, but its never used. And unless I specify `POSTGRES_PASSWORD` env, I will get error saying that no password was supplied . So if that file can be used, I dont understand from where it tries to read it?

P.S. Though is using secrets with environment variables, safe enough (like providing it in `.env` file), because I thought its not a good idea to pass sensitive data such as postgres password like that. So I want to pass it via file instead.
