### ISSUE TITLE
Auth method failed

### ISSUE THREAD

**Issue by felipesuri** [docker-library/postgres#913]
I'm try to deploy my app with postgres, but I gotten this error:

```bash
postgres_1  | 2021-12-03 23:24:15.438 UTC [33] FATAL:  password authentication failed for user "postgres"
postgres_1  | 2021-12-03 23:24:15.438 UTC [33] DETAIL:  Connection matched pg_hba.conf line 100: "host all all all scram-sha-256"
```

I've see #911 and see postgres:14 have an auth bug, I think.

### My docker-compose

```yml
  postgres:
    image: postgres:latest
    env_file:
      - .env
    container_name: jano_postgres
    ports:
      - ${DB_PORT}:${DB_PORT}
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
```

### Error from my prisma (using to connect to db)

```bash
PrismaClientInitializationError: Authentication failed against database server at `jano_postgres`, the provided database credentials for `postgres` are not valid.
```

### My .env

```
# POSTGRES
POSTGRES_USER="postgres"
POSTGRES_PASSWORD="admin"
POSTGRES_DB="holdbtc100"

# Nest run locally
#DB_HOST=localhost
# Nest run in docker, change host to database container name
DB_HOST="jano_postgres"
DB_PORT="5432"

# Prisma database connection
DATABASE_URL="postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DB_HOST}:${DB_PORT}/${POSTGRES_DB}"
SECRET_KEY="secretKeyToDev"
```

I don't know the why, but this .env work on my local machine (created 2 months ago), but in the EC2 machine no.

I need this for yesterday, if you know how I can solve (if postgres:13 or another mode) tell me, please

**Comment by yosifkit** [comment]
I'm uncertain, but would guess that prisma client doesn't yet support `scram-sha-256` authentication or needs to be told to use it?

Options:
- use `postgres:13`
- use a combination of `POSTGRES_INITDB_ARGS=--auth-host=`, `-c password_encryption=`, or `POSTGRES_HOST_AUTH_METHOD` to adjust the password authentication of `postgres:14` (see [this comment](https://github.com/docker-library/postgres/pull/897#issuecomment-944669713)).

**Comment by felipesuri** [comment]
On use `postgres:13` o gotten this:

```bash
PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres_1  |
postgres_1  | 2021-12-04 11:34:53.228 UTC [1] FATAL:  database files are incompatible with server
postgres_1  | 2021-12-04 11:34:53.228 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 14, which is not compatible with this version 13.5 (Debian 13.5-1.pgdg110+1).
```
How I can adjust the password authentication on docker-compose file? Using build args? I really don't know.

**Comment by felipesuri** [comment]
I solved this problem, removing my `app` from a docker image and running `docker run` not  `docker-compose`. 

This solved my problem, but if you know a way to adjust the password auth using docker-compose I accept this too.

**Comment by tianon** [comment]
You should be able to set those same environment variables in a `docker-compose.yml` -- the biggest difference with `docker-compose` is that it's going to try *very* hard to avoid removing your data volume (and to reattach the old volume proactively), and if you want to change these values via environment variables, you have to explicitly delete and reinitialize your database.  See also https://github.com/docker-library/postgres/issues/203#issuecomment-255200501.

(For further help, I would suggest trying a dedicated support forum, such as [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).)

**Comment by fhodun** [comment]
I've found solution to solve this error that appears with latest postgresql in docker compose. 
You need to add this environment variable entry `POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256` in your postgres docker-compose.yml config.

Just like this:
```
  postgres:
    image: "postgres:latest"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=someuser
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=database
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
    volumes:
      - postgres-data:/var/lib/postgresql
```

It's explained on docker postgresql website: [hub.docker.com/_/postgres](https://hub.docker.com/_/postgres/#:~:text=is%20not%20required.-,Note%203%3A,-If%20you%20set) (Environment Variables
 \> POSTGRES_HOST_AUTH_METHOD \> Note 3)
