### ISSUE TITLE
Override default script

### ISSUE THREAD

**Issue by rbogachev** [docker-library/postgres#925]
# Explanation
For some testing purposes, i needed to create a WebAPI for postgres database, which would provide endpoints to dump or restore the database. I decided to run both postgres and web servers inside one container, but i can't understand how to to do that as when i wrote a script to launch everything i was getting an error:
```shell
"root" execution of the PostgreSQL server is not permitted.
The server must be started under an unprivileged user ID to prevent
possible system security compromise.  See the documentation for
more information on how to properly start the server.
```
## Dockerfile
```dockerfile
FROM postgres:12.9

# Web server setup
RUN apt-get update && apt-get -y upgrade
RUN apt-get -y install python3 python3-pip

COPY web_server.py /app/
COPY requirements.txt /app/
RUN pip install -r /app/requirements.txt

# Postgres setup
COPY psql_backup /usr/local/bin/
RUN chmod +x /usr/local/bin/psql_backup

COPY psql_restore /usr/local/bin/
RUN chmod +x /usr/local/bin/psql_restore

# Global setup
COPY launch /usr/local/bin/
RUN chmod +x /usr/local/bin/launch

CMD [ "launch" ]
```
## launch
```shell
#!/bin/bash

uvicorn --workers 1 --app-dir /app web_server:app --host 0.0.0.0 --port 5000 & postgres
```

## docker-compose.yml
```yaml
version: '3'

volumes:
  postgres_data: {}
  postgres_data_backups: {}

services:
  postgres:
    build: ./postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
      - postgres_data_backups:/backups
    ports:
      - '${DB_PORT:-5432}:5432'
      - '${DB_WEB_SERVER_PORT:-5000}:5000'
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    env_file:
      - ./postgres/.env
    restart: "unless-stopped"
```
## env_file
```env
POSTGRES_HOST=postgres
POSTGRES_PORT=5432
POSTGRES_DB=test_db
POSTGRES_USER=user
POSTGRES_PASSWORD=password
```

If anyone knows how to resolve this, any help will be highly appreciated. And if there's an easy way to run postgres server as "root", it will also be applicable (this whole thing is merely for testing, so "security" is not an issue for me)
