### ISSUE TITLE
Docker compose: Error: role "hleb" does not exist. [QUESTION]

### ISSUE THREAD

**Issue by Gleb-Gaiduk** [docker-library/postgres#926]
Hi there.
Kindly ask you to help with docker and Postgres.

- I have a local Postgres database and a project on NestJS.
- I killed 5432 port.

- My Dockerfile
```
FROM node:16.13.1

WORKDIR /app

COPY package.json ./
COPY yarn.lock ./

RUN yarn install

COPY . .

COPY ./dist ./dist
CMD ["yarn", "start:dev"]

```
- My docker-compose.yml
```
version: '3.0'

services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 4000:4000
      - 9229:9229
    command: yarn start:dev
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: postgres
    image: postgres:12
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:

```
- .env

```
DB_TYPE=postgres
DB_HOST=postgres
DB_PORT=5432
DB_USERNAME=hleb
DB_NAME=artwine
DB_PASSWORD=Mypassword

```
- running **sudo docker-compose build** - NO ERRORS

- running **sudo docker-compose up --force-recreate** - ERROR

ERROR [ExceptionHandler] role "hleb" does not exist.

I've tried multiple suggestions from existing issues but nothing helped. 
What am I doing wrong?
Thanks!
