### ISSUE TITLE
environment not used in postgres:14-alpine

### ISSUE THREAD

**Issue by acidflash-moscow** [docker-library/postgres#934]
I'm trying to set environment variables through docker-compose, but after restarting I can't enter under the data that I set. In this case it is POSTGRES_USER: aaa, I can still connect to the database via postgres/postgres.

docker-compose.yml version: "2":

```
  postgres:
      restart: always
      container_name: alpha-postgres
      image: postgres:14-alpine
      ports:
          - 5432:5432
      volumes_from:
          - pg_data
      environment:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: aaa
          PGDATA : /var/lib/postgresql/data/pgdata
  pg_data:
      container_name: alpha-pg_data
      restart: always
      image: alpine:latest
      volumes:
          - ./docker/postgres/data/pgdata:/var/lib/postgresql/data/pgdata
      command: "true"
```
