### ISSUE TITLE
Problem with postgres data volume 

### ISSUE THREAD

**Issue by vallettea** [docker-library/postgres#94]
Hello

I'm using postgres 9.4 image and I wish to have my data persisted under `/data/2life/db`. In compose, I have such a definition where i bind `/data/2life/db` to `/var/lib/postgresql`

```
db:
   image: postgres:9.4
   environment:
      - POSTGRES_USER=rr
      - PGPASSWORD=rr 
      - POSTGRES_PASSWORD=rr
   volumes:
      - /data/2life/db:/var/lib/postgresql
```

however when I inspect my container I notice that the data is persisted in an other volume `/var/lib/docker/volumes...` which i didn't asked.

```
    "Volumes": {
        "/var/lib/postgresql": "/data/2life/db",
        "/var/lib/postgresql/data": "/var/lib/docker/volumes/c90e06963f716494b5d3a3c24a61796dcaee983697ad65c3d76fe069f45d17b1/_data"
    },
```

does someone has an explanation or another way to persist data where we want ?
thx
