### ISSUE TITLE
Ability to set fsync=off with environment variable

### ISSUE THREAD

**Issue by intellix** [docker-library/postgres#968]
It would be a nice convenience if you could set fsync=off for when using this image in integration tests due to how much of a performance boost it gives (in my case it goes from 300sec -> 40sec) using an environment variable.

So instead of:
```yaml
db:
  image: postgres
  command: -c fsync=off
  environment:
    - POSTGRES_USER=myuser
    - POSTGRES_PASSWORD=blahblah
    - POSTGRES_DB=mydb
```

It would be possible to do:
```yaml
db:
  image: postgres
  environment:
    - POSTGRES_USER=myuser
    - POSTGRES_PASSWORD=blahblah
    - POSTGRES_DB=mydb
    - POSTGRES_FSYNC=off
```

I'd like to use `command: -c fsync=off` within my Gitlab CI/CD test step but you only really have access to the env vars for customisation. Currently my workaround is to use bitnami/postgresql which supports it
