### ISSUE TITLE
Questions: How can I define multiple schemas on a postgresql docker instance?

### ISSUE THREAD

**Issue by ghevge** [docker-library/postgres#992]
I have dockized environment that I am working on, which instantiates a postgres DB instance, with a public schema out of the box. All good here. 
But now, I want to create an extra schema with some new tables in it, and I'm not sure how/if I can achieve this.

Any idea how I can achieve this?

My docker-compose postgres definition, currently looks like this:

```
mw-db:
    image: postgres:14.4
    container_name: mw-db
    environment:
      - POSTGRES_DB=mw
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    networks:
      mw-network:
        aliases:
          - mw-db
      default: {}
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - /data/db:/var/lib/postgresql/data
```
