### ISSUE TITLE
docker-compose doesn't populate my postgres database

### ISSUE THREAD

**Issue by IvanCampelo22** [docker-library/postgres#994]
I have a problem, because I do the docker-compose up with postgres, everything works normally, but when I go to my postgres, in psql and give the command \dt, in my database, the message appears: 'Did not find any relations.'. Does anyone know what can it be?

Here is my docker-compose

```
version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports: ["5431:5432"]
    environment:
      - POSTGRES_ENGINE=${POSTGRES_ENGINE}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_ENGINE=${POSTGRES_ENGINE}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    depends_on:
      - db
```

When I run on localhost, without docker-compose, the database is populated, so I believe the problem is in my docker-compose
